export type LibraryItem={title:string;summary:string;kind:"Book"|"Research paper"|"Video"|"Podcast"|"Course"|"Experiment";topic:"Quantum"|"Buddhism"|"Meditation"|"Consciousness"|"Neuroscience";difficulty:"Beginner"|"Intermediate"|"Advanced";author:string;year:string;reliability:"Peer reviewed"|"Primary source"|"Academic"|"Editorially reviewed"};
export const library:LibraryItem[]=[
{title:"Quantum Mechanics: The Theoretical Minimum",summary:"A mathematically serious but approachable route into the basic structure of quantum mechanics.",kind:"Book",topic:"Quantum",difficulty:"Intermediate",author:"Leonard Susskind & Art Friedman",year:"2014",reliability:"Academic"},
{title:"The Feynman Lectures: Quantum Behavior",summary:"A foundational explanation of interference and the double-slit experiment from a master teacher.",kind:"Course",topic:"Quantum",difficulty:"Intermediate",author:"Richard Feynman",year:"1963",reliability:"Academic"},
{title:"Experimental Test of Bell's Inequalities",summary:"A landmark experiment testing quantum correlations against local hidden-variable predictions.",kind:"Research paper",topic:"Quantum",difficulty:"Advanced",author:"Alain Aspect, Philippe Grangier & Gérard Roger",year:"1982",reliability:"Peer reviewed"},
{title:"What the Buddha Taught",summary:"A widely read introduction to core Buddhist teachings grounded in early textual sources.",kind:"Book",topic:"Buddhism",difficulty:"Beginner",author:"Walpola Rahula",year:"1959",reliability:"Academic"},
{title:"In the Buddha's Words",summary:"An organized anthology of discourses from the Pāli Canon with clear contextual introductions.",kind:"Book",topic:"Buddhism",difficulty:"Intermediate",author:"Bhikkhu Bodhi",year:"2005",reliability:"Primary source"},
{title:"Mindfulness meditation and the brain",summary:"A review of proposed neural mechanisms and the methodological limits of meditation research.",kind:"Research paper",topic:"Neuroscience",difficulty:"Advanced",author:"Yi-Yuan Tang, Britta Hölzel & Michael Posner",year:"2015",reliability:"Peer reviewed"},
{title:"Altered Traits",summary:"A measured review of what meditation research supports, what it suggests, and what remains uncertain.",kind:"Book",topic:"Meditation",difficulty:"Beginner",author:"Daniel Goleman & Richard Davidson",year:"2017",reliability:"Editorially reviewed"},
{title:"The Mindful Brain",summary:"An interdisciplinary account of attention, awareness, relationships, and neural integration.",kind:"Book",topic:"Consciousness",difficulty:"Intermediate",author:"Daniel J. Siegel",year:"2007",reliability:"Editorially reviewed"}
];
