export type PathLocale = "en" | "vi";
export type SessionDuration = 30_000 | 180_000 | 300_000 | 600_000;

export const pathOfSeeingConfig = {
  defaultDuration: 300_000 as SessionDuration,
  durations: [180_000, 300_000, 600_000] as SessionDuration[],
  developmentTestDuration: 30_000 as SessionDuration,
  maxRelated: 3,
  maxAmbient: 8,
  maxActive: 12,
  transitionMs: 800,
} as const;

export const pathOfSeeingCopy = {
  en: {
    kicker: "Interactive practice",
    title: "Path of Seeing",
    subtitle: "A quiet constellation of questions. No destination. No right path.",
    duration: "Choose a duration",
    minutes: "minutes",
    sound: "Sound",
    haptic: "Haptic",
    language: "Language",
    on: "On",
    off: "Off",
    begin: "Enter the landscape",
    mute: "Mute sound",
    unmute: "Turn sound on",
    pause: "Session paused",
    resume: "Resume",
    leave: "Return to Practice",
    invitation: "Touch whenever you feel ready.",
    inhale: "Inhale",
    exhale: "Exhale",
    closing: "Thank you for seeing.",
    another: "Begin another session",
    noScore: "Nothing to complete. Nothing to collect.",
    launchTitle: "Path of Seeing",
    launchBody: "Wander through a quiet constellation of reflection prompts beside a moonlit lake.",
    open: "Open experience",
  },
  vi: {
    kicker: "Thực hành tương tác",
    title: "Con Đường Thấy Biết",
    subtitle: "Một chòm sao câu hỏi tĩnh lặng. Không đích đến. Không con đường đúng duy nhất.",
    duration: "Chọn thời lượng",
    minutes: "phút",
    sound: "Âm thanh",
    haptic: "Phản hồi rung",
    language: "Ngôn ngữ",
    on: "Bật",
    off: "Tắt",
    begin: "Bước vào cảnh giới",
    mute: "Tắt âm thanh",
    unmute: "Bật âm thanh",
    pause: "Buổi thực hành đang tạm dừng",
    resume: "Tiếp tục",
    leave: "Trở về Thực hành",
    invitation: "Chạm vào khi bạn cảm thấy sẵn sàng.",
    inhale: "Hít vào",
    exhale: "Thở ra",
    closing: "Cảm ơn bạn đã nhìn thấy.",
    another: "Bắt đầu một buổi khác",
    noScore: "Không có gì cần hoàn thành hay thu thập.",
    launchTitle: "Con Đường Thấy Biết",
    launchBody: "Dạo bước qua một chòm sao suy ngẫm bên mặt hồ dưới ánh trăng.",
    open: "Mở trải nghiệm",
  },
} as const;
