"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight,Atom,BookOpen,Check,LockKeyhole,Sparkles } from "lucide-react";
import { buddhismChapters,dialogueTopics,quantumChapters } from "@/lib/learn-content";
import { Artwork } from "@/components/art/artwork";
export function LearnPaths(){const [complete,setComplete]=useState<string[]>([]);useEffect(()=>setComplete(JSON.parse(localStorage.getItem("qunara-learn-complete")||"[]") as string[]),[]);const qDone=quantumChapters.filter(c=>complete.includes(`quantum/${c.slug}`)).length;const bDone=buddhismChapters.filter(c=>complete.includes(`buddhism/${c.slug}`)).length;const unlocked=qDone===12&&bDone===12;return <main className="book-learn"><header className="book-learn-hero q-shell"><p className="q-kicker">The Qunara library</p><h1>Two paths into<br/>the nature of reality.</h1><p>Begin with matter or mind. Each chapter builds on the last, guided by history, careful explanation, and questions worth carrying beyond the page.</p><div className="learn-progress-summary"><span><Atom/>{qDone}/12 physics chapters</span><span><BookOpen/>{bDone}/12 philosophy chapters</span></div></header><section className="q-shell path-shelf"><PathCard title="The World of Quantum Physics" label="Learning path one" description="From the crisis in classical physics to quantum fields, computing, and the myths that obscure the real wonder." chapters={quantumChapters} done={complete} art="wave"/><PathCard title="The World of Buddhist Philosophy" label="Learning path two" description="From the Buddha’s historical search to emptiness, meditation, compassion, and Buddhism’s modern transformations." chapters={buddhismChapters} done={complete} art="bodhi"/></section><section className={`q-shell dialogue-unlock ${unlocked?"unlocked":""}`}><div className="dialogue-art"><Artwork type="orbit"/></div><div>{unlocked?<Sparkles/>:<LockKeyhole/>}<p className="q-kicker">A third path</p><h2>The Dialogue Between Quantum Physics and Buddhist Philosophy</h2><p>{unlocked?"You have built both foundations. Now the conversation can begin without shortcuts.":"Complete both foundational paths to enter this dialogue. The sequence matters: comparison becomes meaningful only after each tradition can speak in its own voice."}</p><div className="dialogue-topic-preview">{dialogueTopics.slice(0,5).map(x=><span key={x}>{x}</span>)}</div>{unlocked?<Link href="/learn/dialogue">Enter the dialogue <ArrowRight/></Link>:<small>{qDone+bDone} of 24 foundation chapters completed</small>}</div></section></main>}
function PathCard({title,label,description,chapters,done,art}:{title:string;label:string;description:string;chapters:typeof quantumChapters;done:string[];art:"wave"|"bodhi"}){const count=chapters.filter(c=>done.includes(`${c.path}/${c.slug}`)).length;return <motion.article initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} className="learning-path-card"><div className="path-book-art"><Artwork type={art}/><span>{count}/12 complete</span></div><div className="path-book-copy"><p className="q-kicker">{label}</p><h2>{title}</h2><p>{description}</p><div className="path-progress"><i style={{width:`${count/12*100}%`}}/></div><ol>{chapters.map(c=>{const key=`${c.path}/${c.slug}`,finished=done.includes(key);return <li key={c.slug}><Link href={`/learn/${c.path}/${c.slug}`}><span>{finished?<Check/>:String(c.number).padStart(2,"0")}</span><div><h3>{c.title}</h3><small>{c.minutes} min · {c.topics.slice(0,2).join(" · ")}</small></div><ArrowRight/></Link></li>})}</ol></div></motion.article>}
