"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight,Atom,BookOpen,Check,LockKeyhole,Sparkles } from "lucide-react";
import { buddhismChapters,dialogueTopics,quantumChapters } from "@/lib/learn-content";
import { LearnIllustration } from "@/components/learn/learn-illustration";
export function LearnPaths(){const [complete,setComplete]=useState<string[]>([]);useEffect(()=>setComplete(JSON.parse(localStorage.getItem("qunara-learn-complete")||"[]") as string[]),[]);const qDone=quantumChapters.filter(c=>complete.includes(`quantum/${c.slug}`)).length;const bDone=buddhismChapters.filter(c=>complete.includes(`buddhism/${c.slug}`)).length;const unlocked=qDone===12&&bDone===12;return <main className="book-learn"><header className="book-learn-hero q-shell"><p className="q-kicker">The Qunara library</p><h1>Learn to see<br/>more clearly.</h1><p>Begin with matter or mind. Each lesson starts with a human question, follows a story, and gives you something to observe for yourself.</p><div className="learn-progress-summary"><span><Atom/>{qDone}/12 physics chapters</span><span><BookOpen/>{bDone}/12 philosophy chapters</span></div></header><section className="q-shell path-shelf"><PathCard title="The World of Quantum Physics" label="Learning path one" description="A journey from falling apples and glowing furnaces to entanglement, quantum computers, and the edges of what we know." chapters={quantumChapters} done={complete} path="quantum"/><PathCard title="The World of Buddhist Philosophy" label="Learning path two" description="A human story of suffering, attention, compassion, and the many traditions that grew from one teacher’s search." chapters={buddhismChapters} done={complete} path="buddhism"/></section><section className={`q-shell dialogue-unlock ${unlocked?"unlocked":""}`}><div className="dialogue-art"><LearnIllustration path="quantum" chapter={4}/></div><div>{unlocked?<Sparkles/>:<LockKeyhole/>}<p className="q-kicker">A third path</p><h2>The Dialogue Between Quantum Physics and Buddhist Philosophy</h2><p>{unlocked?"You have built both foundations. Now the conversation can begin without shortcuts.":"Complete both foundational paths to enter this dialogue. The sequence matters: comparison becomes meaningful only after each tradition can speak in its own voice."}</p><div className="dialogue-topic-preview">{dialogueTopics.slice(0,5).map(x=><span key={x}>{x}</span>)}</div>{unlocked?<Link href="/learn/dialogue">Enter the dialogue <ArrowRight/></Link>:<small>{qDone+bDone} of 24 foundation chapters completed</small>}</div></section></main>}
function PathCard({title,label,description,chapters,done,path}:{title:string;label:string;description:string;chapters:typeof quantumChapters;done:string[];path:"quantum"|"buddhism"}){const count=chapters.filter(c=>done.includes(`${c.path}/${c.slug}`)).length;return <motion.article initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} className="learning-path-card"><div className="path-book-art"><LearnIllustration path={path}/><span>{count}/12 complete</span></div><div className="path-book-copy"><p className="q-kicker">{label}</p><h2>{title}</h2><p>{description}</p><div className="path-progress"><i style={{width:`${count/12*100}%`}}/></div><ol>{chapters.map(c=>{const key=`${c.path}/${c.slug}`,finished=done.includes(key);return <li key={c.slug}><Link href={`/learn/${c.path}/${c.slug}`}><span>{finished?<Check/>:String(c.number).padStart(2,"0")}</span><div><h3>{c.title}</h3><small>{c.minutes} min · {c.topics.slice(0,2).join(" · ")}</small></div><ArrowRight/></Link></li>})}</ol></div></motion.article>}
