import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Atom, BookOpen, CheckCircle2 } from "lucide-react";
import { Artwork } from "@/components/art/artwork";
import { EvidenceBadge } from "@/components/evidence-badge";
export const metadata:Metadata={title:"Learn",description:"Accessible learning paths through quantum physics and Buddhist philosophy."};
const quantum=["What is Quantum Physics?","Wave Function","Superposition","Entanglement","Observer Effect","Double-Slit Experiment","Quantum Computing","Measurement Problem","Common Misconceptions"];
const buddhism=["Who was the Buddha?","Four Noble Truths","Eightfold Path","Impermanence","Dependent Origination","Emptiness","Non-self","Meditation","Mindfulness","Compassion"];
function World({id,title,subtitle,topics,type,label}:{id:string;title:string;subtitle:string;topics:string[];type:"wave"|"lotus";label:"Scientific evidence"|"Buddhist philosophy"}){return <section className="learn-world" id={id}><div className="learn-world-art"><Artwork type={type}/></div><div><EvidenceBadge kind={label}/><p className="q-kicker">A guided foundation</p><h2>{title}</h2><p className="learn-subtitle">{subtitle}</p><div className="topic-list">{topics.map((topic,i)=><Link href={id==="quantum"?"/quantum":"/buddhism"} key={topic}><span>{String(i+1).padStart(2,"0")}</span>{topic}<ArrowRight/></Link>)}</div></div></section>}
export default function Learn(){return <><header className="page-hero q-shell learn-hero"><p className="q-kicker">Two worlds · carefully taught</p><h1 className="page-title">Learn the ideas.<br/>Keep the distinctions.</h1><p>Begin with either tradition. Every lesson uses plain language, visual explanations, grounded examples, and trustworthy further reading.</p><div className="lesson-includes"><span><CheckCircle2/>Simple explanations</span><span><CheckCircle2/>Original illustrations</span><span><CheckCircle2/>Examples</span><span><CheckCircle2/>Further reading</span></div></header><main className="q-shell learn-worlds"><World id="quantum" title="Quantum Physics" subtitle="A clear path from the strange observations that launched quantum theory to the experiments and technologies shaping modern physics." topics={quantum} type="wave" label="Scientific evidence"/><World id="buddhism" title="Buddhist Philosophy" subtitle="An accessible, historically grounded introduction to teachings, practices, and questions that have developed across many Buddhist traditions." topics={buddhism} type="lotus" label="Buddhist philosophy"/></main><section className="q-shell learn-choice"><Atom/><BookOpen/><div><p className="q-kicker">Not sure where to begin?</p><h2>Start with the question that brought you here.</h2><p>There is no required order. Follow your curiosity, then return to fill in the foundations.</p></div></section></>}
