import Link from "next/link";
import { notFound } from "next/navigation";
import { BookOpen,Clock3,Lightbulb,MessageCircle,Quote,Sparkles,TriangleAlert } from "lucide-react";
import { EvidenceBadge } from "@/components/evidence-badge";
import { LearnIllustration } from "@/components/learn/learn-illustration";
import { allChapters,getChapter,getChapterExperience } from "@/lib/learn-content";
import { LessonActions } from "./lesson-actions";
import { ReaderTools } from "./reader-tools";
export function generateStaticParams(){return allChapters.map(c=>({path:c.path,chapter:c.slug}))}
export function generateMetadata({params}:{params:{path:string;chapter:string}}){const c=getChapter(params.path,params.chapter);return{title:c?.title||"Chapter",description:c?.subtitle}}
export default function ChapterPage({params}:{params:{path:string;chapter:string}}){const c=getChapter(params.path,params.chapter);if(!c)notFound();const experience=getChapterExperience(c);const pathChapters=allChapters.filter(x=>x.path===c.path);const index=pathChapters.findIndex(x=>x.slug===c.slug);const previous=pathChapters[index-1],next=pathChapters[index+1];return <main className="chapter-page"><ReaderTools chapter={c}/><header className="chapter-hero"><LearnIllustration path={c.path} chapter={c.number}/><div className="chapter-hero-wash"/><div className="q-shell"><p>{c.path==="quantum"?"The World of Quantum Physics":"The World of Buddhist Philosophy"} · Chapter {c.number}</p><h1>{experience.question}</h1><blockquote>{c.subtitle}</blockquote><span><Clock3/>{c.minutes} minute read · Foundation</span></div></header><article className="chapter-book"><aside className="chapter-margin"><span>{String(c.number).padStart(2,"0")}</span><p>{c.topics.join(" · ")}</p></aside><div className="chapter-body">
<section className="chapter-care"><p className="chapter-label">Why should I care?</p><h2>The question reaches beyond this page.</h2><p className="chapter-dropcap">{experience.whyCare}</p></section>
<section className="chapter-story"><p className="chapter-label">A story</p><h2>Before there was a definition</h2><p className="chapter-dropcap">{c.history}</p><blockquote>{c.example}</blockquote></section>
<section><p className="chapter-label">A simple explanation</p><h2>Start with the shape of the idea.</h2><p className="chapter-dropcap">{c.lesson[0]}</p><aside className="lesson-plain-language"><Lightbulb/><p><b>In plain language</b>{c.takeaways[0]} Difficult words are useful only when they make the picture clearer.</p></aside></section>
<figure className="chapter-illustration"><LearnIllustration path={c.path} chapter={c.number}/><figcaption>Qunara editorial illustration · a visual explanation, not decorative stock art</figcaption></figure>
<section><div className="chapter-section-heading"><EvidenceBadge kind="Historical context"/><h2>How understanding changed</h2></div><div className="chapter-timeline"><span>Before</span><p>{c.path==="quantum"?"The older picture explained much of the visible world, but a stubborn observation would not fit.":"Teachers inherited older Indian questions, then tested them through debate, community, and contemplative practice."}</p><span>Turning point</span><p>{c.history}</p><span>Now</span><p>{c.takeaways[1]}</p></div></section>
<section className="chapter-deep"><p className="chapter-label">Deep dive · optional</p><h2>Look beneath the first explanation.</h2><p className="chapter-dropcap">{c.lesson[1]||c.lesson[0]}</p><p>{c.path==="quantum"?"The mathematics makes the boundaries exact. You do not need the equations yet, but you should know that the claim is narrower—and stronger—than its popular metaphor.":"Different Buddhist schools developed different readings. The lesson names a shared thread without pretending every tradition speaks with one voice."}</p></section>
<section className="chapter-misunderstanding"><TriangleAlert/><div><p className="chapter-label">Common misunderstanding</p><h2>A tempting shortcut</h2><p>{c.misunderstanding}</p></div></section>
<section className="chapter-matters"><Sparkles/><div><p className="chapter-label">Why it matters</p><h2>What changes after we understand this?</h2><ul>{c.takeaways.map(x=><li key={x}>{x}</li>)}</ul></div></section>
<section className="chapter-reflection"><Quote/><p className="chapter-label">Reflection</p>{c.reflection.map(x=><blockquote key={x}>{x}</blockquote>)}</section>
<section className="chapter-practice"><p className="chapter-label">A practice · 5 minutes</p><h2>Do not only understand it.<br/>Notice something for yourself.</h2><p>{experience.practice}</p><Link href="/practice">Continue in the Practice sanctuary</Link></section>
<section className="chapter-discussion"><MessageCircle/><div><p className="chapter-label">Discussion</p><h2>A thoughtful room begins with a precise question.</h2><blockquote>{experience.discussion}</blockquote><Link href="/community">Share with the community</Link></div></section>
<section className="chapter-takeaways"><p className="chapter-label">Key takeaways</p><h2>Close the book with these.</h2><ol>{c.takeaways.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ol></section>
<section className="chapter-sources"><div><BookOpen/><p className="chapter-label">Books and teachers</p>{c.books.map(x=><p key={x}>{x}</p>)}</div><div><BookOpen/><p className="chapter-label">Research and primary sources</p>{c.references.map(x=><p key={x}>{x}</p>)}</div></section>
<section className="chapter-glossary"><p className="chapter-label">Words worth knowing</p><h2>A small glossary</h2><dl>{c.glossary.map(([term,meaning])=><div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}</dl></section>
<LessonActions chapter={c} previousHref={previous?`/learn/${previous.path}/${previous.slug}`:undefined} nextHref={next?`/learn/${next.path}/${next.slug}`:undefined}/></div></article></main>}
