"use client";
import { FormEvent,useEffect,useState } from "react";
import { Bookmark,Highlighter,MessageCircleQuestion,NotebookPen,Save,X } from "lucide-react";
import type { Chapter } from "@/lib/learn-content";
type Panel="notes"|"ask"|"highlights"|null;
export function ReaderTools({chapter}:{chapter:Chapter}){const key=`${chapter.path}/${chapter.slug}`;const [progress,setProgress]=useState(0);const [bookmarked,setBookmarked]=useState(false);const [panel,setPanel]=useState<Panel>(null);const [notes,setNotes]=useState("");const [highlights,setHighlights]=useState<string[]>([]);const [question,setQuestion]=useState("");const [answer,setAnswer]=useState("");const [streak,setStreak]=useState(1);
useEffect(()=>{setBookmarked((JSON.parse(localStorage.getItem("qunara-bookmarks")||"[]") as string[]).includes(key));setNotes(localStorage.getItem(`qunara-note-${key}`)||"");setHighlights(JSON.parse(localStorage.getItem(`qunara-highlights-${key}`)||"[]") as string[]);const today=new Date().toDateString();const last=localStorage.getItem("qunara-learn-last-day");const current=Number(localStorage.getItem("qunara-learn-streak")||"0");const yesterday=new Date(Date.now()-86400000).toDateString();const next=last===today?Math.max(1,current):last===yesterday?current+1:1;localStorage.setItem("qunara-learn-last-day",today);localStorage.setItem("qunara-learn-streak",String(next));setStreak(next);const scroll=()=>{const el=document.documentElement;setProgress(Math.min(100,Math.max(0,(el.scrollTop/(el.scrollHeight-el.clientHeight))*100)))};window.addEventListener("scroll",scroll,{passive:true});return()=>window.removeEventListener("scroll",scroll)},[key]);
function bookmark(){const saved=JSON.parse(localStorage.getItem("qunara-bookmarks")||"[]") as string[];const next=bookmarked?saved.filter(x=>x!==key):Array.from(new Set([...saved,key]));localStorage.setItem("qunara-bookmarks",JSON.stringify(next));setBookmarked(!bookmarked)}function saveNotes(){localStorage.setItem(`qunara-note-${key}`,notes)}function capture(){const text=window.getSelection()?.toString().trim();if(!text||text.length<3)return;const next=Array.from(new Set([...highlights,text])).slice(-12);setHighlights(next);localStorage.setItem(`qunara-highlights-${key}`,JSON.stringify(next));setPanel("highlights");window.getSelection()?.removeAllRanges()}function ask(e:FormEvent){e.preventDefault();if(!question.trim())return;const lower=question.toLowerCase();if(lower.includes("simple")||lower.includes("mean"))setAnswer(`${chapter.title} is easier to hold if you begin here: ${chapter.lesson[0]}`);else if(lower.includes("example"))setAnswer(chapter.example);else if(lower.includes("misconception")||lower.includes("wrong"))setAnswer(chapter.misunderstanding);else setAnswer(`Return to this distinction: ${chapter.takeaways.join(" ")} Your question may not have a final answer in this chapter, but these boundaries show what the lesson can responsibly claim.`)}
return <><div className="reader-progress" style={{width:`${progress}%`}}/><aside className="reader-tools" aria-label="Reading tools"><button onClick={bookmark} className={bookmarked?"active":""} aria-label={bookmarked?"Remove bookmark":"Bookmark chapter"}><Bookmark fill={bookmarked?"currentColor":"none"}/><span>Save</span></button><button onClick={()=>setPanel(panel==="notes"?null:"notes")}><NotebookPen/><span>Notes</span></button><button onClick={capture}><Highlighter/><span>Highlight</span></button><button onClick={()=>setPanel(panel==="ask"?null:"ask")}><MessageCircleQuestion/><span>Ask</span></button><i>{streak} day{streak===1?"":"s"}</i></aside>{panel&&<aside className="reader-panel"><button className="reader-close" onClick={()=>setPanel(null)} aria-label="Close panel"><X/></button>{panel==="notes"&&<><p>Private notes</p><h2>What do you want to remember?</h2><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write in your own words…"/><button className="reader-save" onClick={saveNotes}><Save/>Save on this device</button></>}{panel==="highlights"&&<><p>Saved highlights</p><h2>Words you paused over</h2>{highlights.length?highlights.map(x=><blockquote key={x}>“{x}”</blockquote>):<small>Select text in the chapter, then press Highlight.</small>}</>}{panel==="ask"&&<><p>Ask Qunara</p><h2>Stay with the difficult part.</h2><small>This lesson assistant answers only from the edited chapter—not from the open web.</small><form onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={`Ask about ${chapter.title.toLowerCase()}…`}/><button>Ask</button></form>{answer&&<blockquote>{answer}</blockquote>}</>}</aside>}</>}
