"use client";
import { FormEvent,useEffect,useMemo,useRef,useState } from "react";
import { AnimatePresence,motion } from "framer-motion";
import { Check,ChevronDown,CloudRain,Headphones,Leaf,LockKeyhole,Pause,Play,Save,Sparkles,VolumeX,Waves,Wind } from "lucide-react";
import { EvidenceBadge } from "@/components/evidence-badge";

type Mood="Calm"|"Restless"|"Uncertain";
type Sound="Silence"|"Forest"|"Rain"|"Ocean";
type Session={id:number;date:string;minutes:number;kind:string;journal:string;x:number;y:number};
const moodGuidance:Record<Mood,{title:string;text:string,prompt:string}>={Calm:{title:"Let quietness become curiosity.",text:"There is no need to improve this moment. Begin by noticing what is already here.",prompt:"What becomes visible when I stop searching?"},Restless:{title:"You do not need to become still.",text:"Restlessness can be observed without being pushed away. Let movement be part of the practice.",prompt:"Where do I feel movement most clearly?"},Uncertain:{title:"Not knowing is welcome here.",text:"You do not need an answer before you begin. Give uncertainty enough room to breathe.",prompt:"Can I meet this uncertainty without naming it a problem?"}};
const seedSessions:Session[]=[{id:1,date:"Jul 8",minutes:8,kind:"Mind observation",journal:"I noticed how quickly a feeling became a story.",x:18,y:64},{id:2,date:"Jul 10",minutes:10,kind:"Meditation",journal:"The sound of rain made the silence feel wider.",x:48,y:28},{id:3,date:"Jul 12",minutes:6,kind:"Reflection",journal:"Change felt less like loss and more like movement.",x:76,y:58}];

function useCountdown(initial:number,onComplete?:()=>void){const [seconds,setSeconds]=useState(initial);const [running,setRunning]=useState(false);const callback=useRef(onComplete);callback.current=onComplete;useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);callback.current?.();return 0}return s-1}),1000);return()=>clearInterval(id)},[running]);return{seconds,setSeconds,running,setRunning}}
function Time({seconds}:{seconds:number}){return <span>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</span>}

export function Sanctuary(){
  const [mood,setMood]=useState<Mood>("Uncertain");const [journal,setJournal]=useState("");const [sessions,setSessions]=useState<Session[]>([]);const [selected,setSelected]=useState<Session|null>(null);const [sound,setSound]=useState<Sound>("Silence");const [shared,setShared]=useState("");const [community,setCommunity]=useState(["I noticed that the breath did not need my help.","Uncertainty softened when I stopped asking it to leave.","Today compassion meant listening without preparing an answer."]);const audioRef=useRef<{context:AudioContext;source:AudioBufferSourceNode;gain:GainNode}|null>(null);
  useEffect(()=>{const raw=localStorage.getItem("qunara-sanctuary-sessions");setSessions(raw?JSON.parse(raw) as Session[]:seedSessions);return()=>stopAudio()},[]);
  function persist(next:Session[]){setSessions(next);localStorage.setItem("qunara-sanctuary-sessions",JSON.stringify(next))}
  function addSession(kind:string,minutes:number,text=journal){const n=sessions.length;const next={id:Date.now(),date:new Date().toLocaleDateString("en-US",{month:"short",day:"numeric"}),minutes,kind,journal:text||"A quiet session without written notes.",x:12+(n*29)%78,y:18+(n*37)%67};persist([...sessions,next]);setJournal("");setSelected(next)}
  const observe=useCountdown(180,()=>addSession("Mind observation",3));const meditate=useCountdown(600,()=>addSession("Meditation",10,"A completed meditation session."));
  function stopAudio(){const a=audioRef.current;if(a){a.gain.gain.setTargetAtTime(0,a.context.currentTime,.1);window.setTimeout(()=>a.context.close(),250);audioRef.current=null}}
  function playSound(next:Sound){stopAudio();setSound(next);if(next==="Silence")return;const Ctx=window.AudioContext||window.webkitAudioContext;const context=new Ctx();const length=context.sampleRate*4;const buffer=context.createBuffer(1,length,context.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(next==="Rain"?.42:next==="Ocean"?.25:.12);const source=context.createBufferSource();source.buffer=buffer;source.loop=true;const filter=context.createBiquadFilter();filter.type=next==="Rain"?"highpass":"lowpass";filter.frequency.value=next==="Rain"?1800:next==="Ocean"?480:1200;const gain=context.createGain();gain.gain.value=.12;source.connect(filter).connect(gain).connect(context.destination);source.start();audioRef.current={context,source,gain}}
  function share(e:FormEvent){e.preventDefault();if(!shared.trim())return;setCommunity([shared.trim(),...community]);setShared("")}
  const totals=useMemo(()=>({minutes:sessions.reduce((a,s)=>a+s.minutes,0),journals:sessions.filter(s=>!s.journal.startsWith("A completed")&&!s.journal.startsWith("A quiet")).length,streak:Math.min(sessions.length,7)}),[sessions]);
  return <main className="sanctuary">
    <div className="sanctuary-particles" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i} style={{left:`${(i*43)%97}%`,top:`${(i*67)%91}%`,animationDelay:`${i*.37}s`}}/>)}</div>
    <section className="sanctuary-hero q-shell"><motion.p initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="q-kicker">Today&apos;s journey</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.1}}>Welcome to<br/>this moment.</motion.h1><p>Nothing to achieve. Nothing to prove. Choose what feels closest to your inner weather.</p><div className="mood-choices" role="group" aria-label="Choose your current mood">{(["Calm","Restless","Uncertain"] as Mood[]).map(x=><button key={x} className={mood===x?"active":""} onClick={()=>setMood(x)}>{x}</button>)}</div><AnimatePresence mode="wait"><motion.div key={mood} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="mood-guidance"><Sparkles/><div><h2>{moodGuidance[mood].title}</h2><p>{moodGuidance[mood].text}</p></div><span>{moodGuidance[mood].prompt}</span></motion.div></AnimatePresence><a className="journey-down" href="#observe">Begin gently <ChevronDown/></a></section>

    <section className="sanctuary-section q-shell" id="observe"><div className="sanctuary-heading"><p className="q-kicker">01 · Mind observation</p><h2>Watch the mind<br/>without holding it.</h2><p>A short guided pause. Thoughts may appear. Let each one pass without following or resisting it.</p></div><div className="observe-glass"><div className={`observation-orbit ${observe.running?"active":""}`}><i/><i/><Time seconds={observe.seconds}/><small>{observe.running?"Notice. Allow. Return.":"Three quiet minutes"}</small></div><div className="observe-actions"><button onClick={()=>observe.setRunning(!observe.running)}>{observe.running?<Pause/>:<Play/>}{observe.running?"Pause":"Begin observation"}</button><button onClick={()=>{observe.setRunning(false);observe.setSeconds(180)}}>Reset</button></div><label htmlFor="mind-journal"><LockKeyhole/> Optional private journal</label><textarea id="mind-journal" value={journal} onChange={e=>setJournal(e.target.value)} placeholder="What did you notice? Your words remain on this device."/><button className="save-practice" onClick={()=>addSession("Mind observation",Math.max(1,Math.ceil((180-observe.seconds)/60)))}><Save/>Complete &amp; keep reflection</button></div></section>

    <section className="daily-reflection"><div className="q-shell"><div className="sanctuary-heading"><p className="q-kicker">02 · Daily reflection</p><h2>Two lenses.<br/>One careful question.</h2></div><div className="reflection-lenses"><article><EvidenceBadge kind="Scientific evidence"/><Waves/><h3>Quantum uncertainty</h3><p>Quantum theory predicts probabilities for measurement outcomes. This uncertainty is mathematically precise; it is not simply a feeling or a lack of knowledge.</p></article><article><EvidenceBadge kind="Buddhist philosophy"/><Leaf/><h3>Impermanence</h3><p>Buddhist teachings invite us to observe that conditioned experiences arise, change, and pass. This insight supports a less grasping relationship with life.</p></article></div><div className="reflection-question"><span>Today&apos;s question</span><blockquote>How might I meet change with attention rather than immediate resistance?</blockquote><p>These ideas can resonate without being equivalent. Quantum physics does not scientifically prove Buddhist teaching.</p></div></div></section>

    <section className="sanctuary-section q-shell meditation-sanctuary"><div className="sanctuary-heading"><p className="q-kicker">03 · Meditation</p><h2>Make room<br/>for silence.</h2><p>Choose an atmosphere, settle into a comfortable position, and let the timer hold time for you.</p></div><div className="meditation-glass"><div className={`breathing-sphere ${meditate.running?"active":""}`}><span>{meditate.running?"Breathe":"Ready"}</span></div><div className="meditation-time"><Time seconds={meditate.seconds}/><div><button onClick={()=>meditate.setSeconds(s=>Math.max(60,s-300))}>− 5</button><button className="meditate-play" onClick={()=>meditate.setRunning(!meditate.running)}>{meditate.running?<Pause/>:<Play/>}<span className="sr-only">{meditate.running?"Pause":"Start"} meditation</span></button><button onClick={()=>meditate.setSeconds(s=>s+300)}>+ 5</button></div></div><div className="sound-options" role="group" aria-label="Ambient sound">{(["Silence","Forest","Rain","Ocean"] as Sound[]).map(x=>{const Icon=x==="Silence"?VolumeX:x==="Forest"?Wind:x==="Rain"?CloudRain:Waves;return <button className={sound===x?"active":""} onClick={()=>playSound(x)} key={x}><Icon/>{x}</button>})}</div><button className="save-practice" onClick={()=>addSession("Meditation",Math.max(1,Math.ceil((600-meditate.seconds)/60)),`Meditated with ${sound.toLowerCase()} ambience.`)}><Check/>Complete session</button></div></section>

    <section className="inner-sky-section"><div className="q-shell"><div className="sanctuary-heading"><p className="q-kicker">04 · Inner sky</p><h2>Every pause<br/>leaves a light.</h2><p>Each completed practice becomes a star. There is no score here—only a quiet record of moments when you chose to notice.</p></div><div className="inner-sky" aria-label="Your completed sessions">{sessions.map((s,i)=><motion.button initial={{scale:0}} whileInView={{scale:1}} transition={{delay:i*.05}} key={s.id} style={{left:`${s.x}%`,top:`${s.y}%`}} className={selected?.id===s.id?"selected":""} onClick={()=>setSelected(s)} aria-label={`Open ${s.date} reflection`}><i/></motion.button>)}<span className="sky-horizon"/></div><AnimatePresence>{selected&&<motion.aside initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="star-entry"><button onClick={()=>setSelected(null)}>×</button><span>{selected.date} · {selected.kind} · {selected.minutes} min</span><p>“{selected.journal}”</p></motion.aside>}</AnimatePresence></div></section>

    <section className="sanctuary-section q-shell growth-section"><div className="growth-tree" aria-label={`Symbolic growth tree with ${sessions.length} sessions`}><svg viewBox="0 0 500 560" role="img"><path className="tree-ground" d="M55 515 Q250 475 445 515"/><path className="tree-trunk" d="M252 500 C245 400 270 315 250 205 C240 150 255 105 260 65 M252 370 C205 335 165 300 140 242 M255 320 C300 280 330 240 348 183 M250 250 C215 215 200 170 198 125"/>{Array.from({length:Math.min(18,sessions.length*2+3)},(_,i)=><motion.ellipse initial={{scale:0}} whileInView={{scale:1}} transition={{delay:i*.06}} key={i} cx={120+(i*83)%265} cy={105+(i*67)%265} rx="18" ry="8" transform={`rotate(${(i*37)%140} ${120+(i*83)%265} ${105+(i*67)%265})`}/>)}</svg></div><div className="sanctuary-heading"><p className="q-kicker">05 · Growth tree</p><h2>Growth has<br/>its own season.</h2><p>This tree changes slowly as your practice continues. It is symbolic, not competitive—a reminder that roots often deepen before branches become visible.</p><span className="tree-stage"><Leaf/> {sessions.length<5?"A seedling taking root":sessions.length<12?"New branches appearing":"A canopy quietly forming"}</span></div></section>

    <section className="community-reflections"><div className="q-shell"><div className="sanctuary-heading"><p className="q-kicker">06 · Community reflections</p><h2>Quiet insights,<br/>shared anonymously.</h2><p>Read what others noticed, or leave a reflection without a profile. Submissions are held to a respectful moderation standard.</p></div><div className="reflection-stream">{community.map((x,i)=><motion.blockquote initial={{opacity:0}} whileInView={{opacity:1}} key={`${x}-${i}`}>“{x}”<span>Anonymous reflection</span></motion.blockquote>)}</div><form onSubmit={share}><label htmlFor="share-reflection">Offer a reflection</label><textarea id="share-reflection" value={shared} onChange={e=>setShared(e.target.value)} placeholder="What became a little clearer?"/><div><small>Shared anonymously · Respectfully moderated</small><button>Submit for review</button></div></form></div></section>

    <section className="history-section q-shell"><div className="sanctuary-heading"><p className="q-kicker">07 · Practice history</p><h2>A record,<br/>not a ranking.</h2></div><div className="history-stats"><article><span>{totals.streak}</span><p>Days practiced</p></article><article><span>{sessions.length}</span><p>Total sessions</p></article><article><span>{totals.minutes}</span><p>Minutes in practice</p></article><article><span>{totals.journals}</span><p>Journal entries</p></article></div><div className="history-chart"><div>{sessions.slice(-12).map((s,i)=><motion.i initial={{height:0}} whileInView={{height:`${Math.max(12,Math.min(100,s.minutes*7))}%`}} transition={{delay:i*.05}} key={s.id}><span>{s.minutes}m</span></motion.i>)}</div><p><span>Earlier</span><span>Today</span></p></div><footer><Headphones/><p>You have spent {totals.minutes} intentional minutes returning to experience.</p></footer></section>
  </main>;
}

declare global{interface Window{webkitAudioContext:typeof AudioContext}}
