import Link from "next/link";
import { ArrowRight, Atom, BookOpen, Brain, Clock3, Headphones, MessageCircle, Sparkles } from "lucide-react";
import { Artwork } from "@/components/art/artwork";
import { EvidenceBadge } from "@/components/evidence-badge";

const pillars=[{icon:Atom,title:"Science",eyebrow:"Understand the outer world",text:"Clear, evidence-led guides to quantum mechanics, experiments, and the questions physics is still working to answer.",href:"/learn#quantum"},{icon:BookOpen,title:"Wisdom",eyebrow:"Explore the inner world",text:"Buddhist philosophy in historical context—from impermanence and non-self to compassion and interdependence.",href:"/learn#buddhism"},{icon:Brain,title:"Practice",eyebrow:"Bring insight into life",text:"Meditation, reflection, and humane daily practices that turn interesting ideas into a wiser way of living.",href:"/practice"}];
export default function Home(){return <div className="q-home"><section className="q-hero"><Artwork type="orbit" className="q-hero-art"/><div className="q-hero-wash"/><div className="q-shell q-hero-content"><p className="q-kicker">Science · Wisdom · Conscious living</p><h1>Explore<br/><em>Reality.</em></h1><p className="q-hero-lead">A community exploring quantum physics, Buddhist philosophy, consciousness, and the practice of living wisely.</p><div className="q-hero-actions"><Link href="/learn" className="q-btn-primary">Start Learning <ArrowRight/></Link><Link href="/explore" className="q-btn-secondary">Explore Connections</Link><Link href="/practice" className="q-text-link">Practice Today <Clock3/></Link></div></div><div className="q-hero-note"><span>Q</span><p>Two lenses.<br/>One shared curiosity.</p></div></section>
<section className="q-shell q-pillars"><div className="q-section-intro"><p className="q-kicker">Three ways in</p><h2>Understand. Reflect. Practice.</h2></div><div className="q-pillar-grid">{pillars.map(({icon:Icon,...p},i)=><Link href={p.href} className="q-pillar" key={p.title}><span>0{i+1}</span><Icon/><p>{p.eyebrow}</p><h3>{p.title}</h3><small>{p.text}</small><b>Enter this path <ArrowRight/></b></Link>)}</div></section>
<section className="q-feature"><div className="q-shell q-feature-grid"><div className="q-feature-art"><Artwork type="wave"/><span>Featured inquiry</span></div><article><EvidenceBadge kind="Scientific evidence"/><p className="q-kicker">Featured article · 12 min read</p><h2>What the double-slit experiment actually tells us.</h2><p>The experiment is often used to make sweeping claims about consciousness. The real story—about interference, measurement, and probability—is more precise and more fascinating.</p><Link href="/research">Read the grounded guide <ArrowRight/></Link></article></div></section>
<section className="q-shell q-today"><div className="q-section-intro"><p className="q-kicker">For today</p><h2>Small moments of discovery.</h2></div><div className="q-today-grid"><article className="q-reflection"><Sparkles/><EvidenceBadge kind="Personal reflection"/><blockquote>“What did you notice today without immediately judging it?”</blockquote><Link href="/practice#reflection">Write a reflection <ArrowRight/></Link></article><article><MessageCircle/><p className="q-kicker">Latest discussion</p><h3>Does observing always mean consciousness?</h3><p>Community members untangle a common confusion around measurement.</p><Link href="/community">Join the conversation <ArrowRight/></Link></article><article><Headphones/><p className="q-kicker">Featured meditation</p><h3>Ten minutes with change</h3><p>A quiet practice for noticing sensations arise, transform, and pass.</p><Link href="/practice">Begin practice <ArrowRight/></Link></article></div></section></div>}
