"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Brain, BriefcaseBusiness, ChevronDown, CloudSun, Eye, GitBranch, Heart, MessageCircle, Network, RefreshCw, Sparkles, Trees } from "lucide-react";
import { OpeningStory, SourceDrawer } from "./investigation-system";

type SystemKey = "Forest" | "Economy" | "Climate" | "Family" | "Emotion";
const systems: Record<SystemKey, { icon: typeof Trees; intro: string; nodes: string[] }> = {
  Forest: { icon: Trees, intro: "A forest emerges from relationships among living and nonliving conditions. Remove one and the others do not simply disappear—they respond.", nodes: ["Sunlight", "Water", "Soil", "Fungi", "Plants", "Animals"] },
  Economy: { icon: BriefcaseBusiness, intro: "Prices and livelihoods arise through institutions, labor, resources, trust, transport, policy, and countless decisions.", nodes: ["Labor", "Resources", "Credit", "Demand", "Transport", "Policy"] },
  Climate: { icon: CloudSun, intro: "Climate patterns arise through interacting oceans, atmosphere, land, ice, life, and energy from the sun.", nodes: ["Ocean", "Air", "Land", "Ice", "Life", "Sunlight"] },
  Family: { icon: Heart, intro: "A family moment is shaped by histories, needs, habits, care, communication, and pressures outside the home.", nodes: ["History", "Needs", "Care", "Habits", "Stress", "Speech"] },
  Emotion: { icon: Brain, intro: "An emotion may depend on body state, memory, interpretation, attention, surroundings, and what just happened.", nodes: ["Body", "Memory", "Meaning", "Attention", "Setting", "Event"] },
};

const sources = [
  { kind: "Buddhist text", title: "SN 12.20 — Conditions", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "Distinguishes dependent origination from dependently arisen phenomena and presents specific conditional links in the arising of suffering.", href: "https://suttacentral.net/sn12.20/en/bodhi" },
  { kind: "Buddhist text", title: "SN 12.37 — Not Yours", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "States the formula of arising and cessation and connects it to the traditional sequence from ignorance through aging, death, and distress.", href: "https://suttacentral.net/sn12.37/en/bodhi" },
  { kind: "Buddhist text", title: "SN 12.2 — Analysis", publisher: "SuttaCentral · translation by Bhikkhu Sujato", note: "Defines the factors in the traditional twelve-link presentation and emphasizes particular dependencies rather than a universal slogan.", href: "https://suttacentral.net/sn12.2/en/sujato" },
  { kind: "Systems science", title: "Systems Biology", publisher: "NIH Intramural Research Program", note: "Describes studying interactions among parts and system properties that cannot be inferred from isolated components alone.", href: "https://irp.nih.gov/our-research/scientific-focus-areas/systems-biology" },
  { kind: "Ecology", title: "What Is an Ecosystem?", publisher: "National Geographic Society", note: "Introduces ecosystems through interactions among organisms and physical environments.", href: "https://education.nationalgeographic.org/resource/ecosystem/" },
  { kind: "Quantum physics boundary", title: "Quantum Entanglement", publisher: "Caltech Science Exchange", note: "Explains entanglement as a specific experimentally studied quantum relationship, not a general theory that everything influences everything else.", href: "https://scienceexchange.caltech.edu/topics/quantum-science-explained/entanglement" },
];

export function DependentOriginationInvestigation() {
  const [system, setSystem] = useState<SystemKey>("Forest");
  const [removed, setRemoved] = useState<number | null>(null);
  const active = systems[system];

  const chooseSystem = (name: SystemKey) => { setSystem(name); setRemoved(null); };

  return <article className="dependent-investigation" id="dependent-origination">
    <header className="dependent-opening"><NetworkArtwork/><div className="dependent-wash"/><div className="q-shell"><p className="q-kicker">Investigation 04 · Ancient observations, modern echoes</p><h1>Dependent Origination<br/><em>Nothing Exists Alone.</em></h1><p>A seed waits in dark soil. Rain arrives. Fungi trade nutrients at its roots. Light reaches a new leaf. No single condition is the forest—and without conditions, there is no tree standing by itself.</p><a href="#conditional-formula">Trace the conditions <ChevronDown/></a></div></header>

    <OpeningStory className="dependent-story q-shell" kicker="A morning in the forest" title="The tree has no solitary beginning."><p>Ask where the tree began and the answer keeps moving. The seed came from another tree. That tree depended on soil built by older life. Water arrived through weather. Its carbon came from the air; its energy from sunlight.</p><p>Yet dependent origination is more precise than this forest story. The Buddhist teaching does not merely announce that everything touches everything. It examines particular conditions through which suffering arises—and the conditions through which it can cease.</p><p>The forest, economy, climate, family, and emotion examples below are analogies. They can train our attention to relationships, but they are not substitutes for the canonical sequence.</p></OpeningStory>

    <section className="conditional-formula" id="conditional-formula"><div className="q-shell"><p className="q-kicker">The conditional formula</p><blockquote><span>“When this exists,</span>that comes to be.<br/><span>With the arising of this,</span>that arises.”<cite>SN 12.37, translated by Bhikkhu Bodhi</cite></blockquote><div><p>This formula describes conditionality: something happens because the conditions it needs are present. Think of a flame: it depends on fuel, oxygen, and heat, not on one isolated cause. The teaching does not claim that every event directly causes every other event.</p><p>The reverse matters just as much. Remove a condition the process truly needs—like fuel from the flame—and what depends on it cannot continue in the same way. This is why the teaching is practical: it asks which conditions can be understood and changed.</p></div></div></section>

    <section className="dependent-teaching q-shell"><header><EvidenceTag label="Buddhist teaching" value="Direct textual basis" tone="strong"/><p className="q-kicker">What it actually means</p><h2>A map of suffering<br/>and a possibility of release.</h2></header><div className="twelve-links"><span>Ignorance</span><i/><span>Choices</span><i/><span>Consciousness</span><i/><span>Name & form</span><i/><span>Six senses</span><i/><span>Contact</span><i/><span>Feeling</span><i/><span>Craving</span><i/><span>Grasping</span><i/><span>Continued existence</span><i/><span>Birth</span><i/><span>Aging, death & distress</span></div><div className="dependent-precision"><article><GitBranch/><h3>Not one first cause</h3><p>The teaching attends to patterned dependence. Traditions interpret the links across moments, lifetimes, and psychological processes, so one diagram should not pretend to settle every interpretation.</p></article><article><RefreshCw/><h3>Arising and cessation</h3><p>Its liberating force lies in reversibility: when ignorance, craving, and grasping are no longer fed, the processes depending on them can change and cease.</p></article></div></section>

    <section className="network-lab"><div className="q-shell"><header><p className="q-kicker">Interactive network</p><h2>Remove one condition.<br/>Watch the system respond.</h2><p>This model is educational, not predictive. Real systems have more conditions, feedback loops, delays, thresholds, and unknowns than six nodes can show.</p></header><div className="system-tabs" role="group" aria-label="Example system">{(Object.keys(systems) as SystemKey[]).map(name => { const Icon = systems[name].icon; return <button key={name} aria-pressed={system === name} className={system === name ? "active" : ""} onClick={() => chooseSystem(name)}><Icon/>{name}</button>; })}</div><div className="network-stage"><div className={`condition-network ${removed !== null ? "changed" : ""}`}><svg viewBox="0 0 600 520" aria-hidden="true">{active.nodes.map((_, index) => active.nodes.slice(index + 1).map((__, offset) => { const other = index + offset + 1; const a = nodePosition(index); const b = nodePosition(other); return <motion.line key={`${index}-${other}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} animate={{ opacity: removed === index || removed === other ? .03 : removed === null ? .24 : .11 }} stroke="#d5ac4d"/>; }))}</svg>{active.nodes.map((node, index) => { const pos = nodePosition(index); const isRemoved = removed === index; return <motion.button key={node} className={isRemoved ? "removed" : ""} style={{ left: `${pos.x / 6}%`, top: `${pos.y / 5.2}%` }} animate={{ scale: isRemoved ? .7 : removed === null ? 1 : .88 + (index % 3) * .05, x: removed !== null && !isRemoved ? ((index % 2 ? 1 : -1) * 8) : 0, opacity: isRemoved ? .2 : 1 }} onClick={() => setRemoved(isRemoved ? null : index)} aria-pressed={isRemoved}><i/><span>{node}</span></motion.button>; })}<div className="network-center"><Network/><span>{system}</span></div></div><motion.article key={`${system}-${removed}`} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><span>{removed === null ? "System in relation" : "Condition removed"}</span><h3>{removed === null ? system : active.nodes[removed!]}</h3><p>{removed === null ? active.intro : `${active.nodes[removed!]} has been removed from this simplified model. Connections weaken and the remaining conditions reorganize. This does not mean the whole real system instantly vanishes; effects depend on redundancy, timing, feedback, and context.`}</p>{removed !== null && <button onClick={() => setRemoved(null)}><RefreshCw/>Restore condition</button>}</motion.article></div></div></section>

    <section className="real-world-conditions q-shell"><header><p className="q-kicker">Five everyday lenses</p><h2>Look for conditions,<br/>not isolated things.</h2></header><div>{(Object.entries(systems) as [SystemKey, typeof systems[SystemKey]][]).map(([name, item]) => { const Icon = item.icon; return <article key={name}><Icon/><span>{name}</span><p>{item.intro}</p></article>; })}</div></section>

    <section className="systems-comparison"><div className="q-shell"><header><p className="q-kicker">Modern science</p><h2>Systems, networks,<br/>ecology, complexity.</h2></header><div><p>Systems thinking asks how parts change one another inside a larger whole. Network science draws those parts as points and their relationships as links. Ecology studies organisms together with soil, water, climate, and other surroundings.</p><p>Complex-systems research studies effects that appear only when many parts interact. <b>Emergence</b> is a group pattern no single part produces alone, like traffic forming from many drivers. <b>Feedback</b> means an effect circles back to strengthen or weaken its cause. <b>Nonlinearity</b> means twice the input may produce much more—or much less—than twice the result.</p><p>Scientists test these ideas with mathematical models, observations, experiments, and simulations. The resemblance to conditionality can be useful, but these fields do not contain the Buddhist account of craving, grasping, suffering, or freedom from suffering.</p></div></div></section>

    <section className="entanglement-boundary q-shell"><div><Sparkles/><p className="q-kicker">A crucial boundary</p><h2>Dependent origination<br/><span>≠</span><br/>quantum entanglement.</h2></div><div><p>Quantum entanglement is a specific physical relationship between quantum systems, described mathematically and tested experimentally. It is not a scientific name for social connection, ecological dependence, emotion, karma, or universal oneness.</p><p>Dependent origination is a Buddhist teaching about conditioned arising and cessation, especially the arising and ending of suffering. Similar words such as “relation” or “dependence” do not make the two concepts equivalent.</p><EvidenceTag label="Scientific equivalence" value="None established" tone="none"/></div></section>

    <section className="dependent-reflection"><div className="q-shell"><div><Brain/><p className="q-kicker">Reflection · Trace an emotion</p><h2>Choose one emotion.<br/>Find five conditions.</h2></div><ol><li><span>01</span><div><b>Body</b><p>What sensations, energy, hunger, pain, or fatigue were present?</p></div></li><li><span>02</span><div><b>Event</b><p>What happened immediately before the emotion appeared?</p></div></li><li><span>03</span><div><b>Interpretation</b><p>What meaning did your mind give that event?</p></div></li><li><span>04</span><div><b>History</b><p>What memory, habit, or earlier experience shaped the response?</p></div></li><li><span>05</span><div><b>Environment</b><p>Who, what, and which pressures were around you?</p></div></li></ol><aside>This is reflection, not diagnosis. Conditions help explain an emotion; they do not make it unreal or remove responsibility for how we respond.</aside></div></section>

    <section className="dependent-close q-shell"><article><Eye/><p className="q-kicker">Practice · Pause at one link</p><p>When a strong feeling appears, name the contact, the feeling tone, and the first sign of wanting or resistance. Ask which condition can be met with more care.</p><Link href="/practice">Continue in Practice <ArrowRight/></Link></article><article><MessageCircle/><p className="q-kicker">Community discussion</p><p>Which condition in your life has changed a whole system—family, work, community, or inner life—in a way you did not expect?</p><Link href="/community">Discuss with care <ArrowRight/></Link></article></section>

    <SourceDrawer className="dependent-sources" subtitle="Canonical translations, systems research, ecology, and the quantum boundary" sources={sources} note="The five modern examples are analogies for learning to notice conditions. They should not be presented as canonical definitions of dependent origination or as evidence that Buddhist doctrine anticipated modern systems science."/>
  </article>;
}

function nodePosition(index: number) { const angle = (index * Math.PI * 2) / 6 - Math.PI / 2; return { x: 300 + Math.cos(angle) * 205, y: 260 + Math.sin(angle) * 195 }; }
function EvidenceTag({ label, value, tone }: { label: string; value: string; tone: "strong" | "none" }) { return <div className={`evidence-pill ${tone}`}><div><span>{label}</span><b>{value}</b></div></div>; }
function NetworkArtwork() { return <svg className="dependent-artwork" viewBox="0 0 1400 860" role="img" aria-label="An illuminated network grows from roots into a forest, city, cloud, family, and mind"><defs><linearGradient id="network-bg" x2="1" y2="1"><stop stopColor="#07111d"/><stop offset=".5" stopColor="#132b32"/><stop offset="1" stopColor="#171d31"/></linearGradient><radialGradient id="node-glow"><stop stopColor="#e3c16e" stopOpacity=".7"/><stop offset="1" stopColor="#d5ac4d" stopOpacity="0"/></radialGradient></defs><rect width="1400" height="860" fill="url(#network-bg)"/><g stroke="#b9ceba" strokeOpacity=".17">{Array.from({ length: 30 }, (_, i) => <line key={i} x1={620 + (i * 113) % 700} y1={100 + (i * 71) % 620} x2={620 + ((i + 7) * 113) % 700} y2={100 + ((i + 11) * 71) % 620}/>)}</g>{Array.from({ length: 34 }, (_, i) => <g key={i}><circle cx={620 + (i * 113) % 700} cy={100 + (i * 71) % 620} r="25" fill="url(#node-glow)"/><circle cx={620 + (i * 113) % 700} cy={100 + (i * 71) % 620} r={i % 7 === 0 ? 5 : 2} fill={i % 3 ? "#b8cec1" : "#d9b75f"}/></g>)}<path d="M1040 710q-20-160-4-310m2 82q-90-85-160-50m160-12q88-92 160-50m-164 150q-74-72-130-42m133-15q70-72 132-41" fill="none" stroke="#84a886" strokeWidth="7" strokeLinecap="round" opacity=".55"/><path d="M1035 710q-95 20-180 80m180-80q100 18 190 78m-190-78q-20 55-5 100" fill="none" stroke="#9d7448" strokeWidth="4" opacity=".5"/></svg>; }
