"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Award, CheckCircle2, ChevronDown, ExternalLink, Eye, FlaskConical, Gauge, MessageCircle, Radio, Sparkles, TriangleAlert } from "lucide-react";
import { MisconceptionPanel, OpeningStory, SourceDrawer } from "./investigation-system";

type Reveal = "Similarities" | "Differences" | "Misconceptions" | "Sources" | "Practice";

const sources = [
  { kind: "Prize record", title: "The Nobel Prize in Physics 2022", publisher: "Nobel Prize Outreach", note: "Official prize summary for Alain Aspect, John F. Clauser, and Anton Zeilinger and their work on entangled photons, Bell inequalities, and quantum information science.", href: "https://www.nobelprize.org/prizes/physics/2022/summary/" },
  { kind: "Physics explanation", title: "How entanglement became a powerful tool", publisher: "Nobel Prize Outreach", note: "Accessible historical explanation of Bell's insight and the experimental developments by Clauser, Aspect, and Zeilinger.", href: "https://www.nobelprize.org/prizes/physics/2022/popular-information/" },
  { kind: "Experiment", title: "A strong loophole-free test of local realism", publisher: "National Institute of Standards and Technology", note: "Reports a loophole-free Bell test with entangled photon pairs and spacelike-separated measurement events.", href: "https://www.nist.gov/publications/strong-loophole-free-test-local-realism" },
  { kind: "Buddhist text", title: "SN 12.20 — Conditions", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "Presents dependent origination as specific conditionality and distinguishes it from dependently arisen phenomena.", href: "https://suttacentral.net/sn12.20/en/bodhi" },
  { kind: "Buddhist text", title: "SN 12.37 — Not Yours", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "States the arising-and-cessation formula in the context of the traditional sequence concerning suffering.", href: "https://suttacentral.net/sn12.37/en/bodhi" },
];

export function EntanglementDialogue() {
  const [basis, setBasis] = useState<"Vertical" | "Diagonal">("Vertical");
  const [measured, setMeasured] = useState(false);
  const [reveal, setReveal] = useState<Reveal>("Similarities");

  const measure = () => { setMeasured(false); requestAnimationFrame(() => setMeasured(true)); };

  return <article className="entanglement-dialogue" id="quantum-dialogue">
    <header className="entanglement-opening"><EntanglementArtwork/><div className="entanglement-wash"/><div className="q-shell"><p className="q-kicker">Quantum Dialogue · Investigation 01</p><h1>Quantum Entanglement<br/><em>and Interdependence.</em></h1><p>Two particles leave one source in opposite directions. Far apart, they are measured. Across many trials, their results fit together more strongly than a certain classical picture allows. The resemblance to interdependence is evocative. It is also easy to misuse.</p><a href="#entanglement-basics">Begin without equations <ChevronDown/></a></div></header>

    <OpeningStory className="entanglement-story q-shell" id="entanglement-basics" kicker="Begin with the experiment" title={<>One source.<br/>Two measurement stations.</>}><p>A laboratory prepares pairs of photons—small packets of light—in an entangled state. “Entangled” means quantum theory must describe the pair with one shared mathematical state, even after the photons travel apart. One photon goes to Alice’s detector; the other goes to Bob’s. Each detector can be turned to test polarization, the orientation in which light oscillates.</p><p>A single result looks random. The pattern appears only after Alice and Bob compare many recorded trials through ordinary communication. Quantum mechanics predicts correlations: statistical relationships between their lists of results.</p><p>Entanglement is not an invisible message passing between minds or particles. The “joint state” is the mathematical description of the pair as a whole. Its predictions are tested by preparing and measuring many pairs in the same way.</p></OpeningStory>

    <section className="particle-lab q-shell"><header><p className="q-kicker">Interactive concept model</p><h2>Change the detector.<br/>Compare the pattern.</h2><p>This animation illustrates correlated outcomes. It is not a Bell experiment, a simulation of quantum probabilities, or live laboratory data.</p></header><div className="particle-stage"><div className={`particle-pair ${measured ? "measured" : ""} ${basis.toLowerCase()}`}><motion.div animate={{ x: measured ? -105 : 0 }}><i/><span>Alice</span><b>{measured ? (basis === "Vertical" ? "↕" : "⤢") : "?"}</b></motion.div><span className="pair-source"><Sparkles/>Shared preparation</span><motion.div animate={{ x: measured ? 105 : 0 }}><i/><span>Bob</span><b>{measured ? (basis === "Vertical" ? "↕" : "⤢") : "?"}</b></motion.div></div><article><span>Detector basis</span><div><button className={basis === "Vertical" ? "active" : ""} onClick={() => { setBasis("Vertical"); setMeasured(false); }}>Vertical</button><button className={basis === "Diagonal" ? "active" : ""} onClick={() => { setBasis("Diagonal"); setMeasured(false); }}>Diagonal</button></div><button className="measure-pair" onClick={measure}><Gauge/>Measure illustrative pair</button><p>{measured ? "The matching symbols are a teaching simplification. Real Bell tests use many trials, several settings, probability distributions, and statistical analysis." : "Choose a basis, then reveal one illustrative correlated outcome."}</p></article></div></section>

    <section className="bell-history"><div className="q-shell"><header><p className="q-kicker">Einstein, Bell, and experiment</p><h2>A philosophical dispute<br/>became testable.</h2></header><ol><li><span>1935</span><div><h3>Einstein, Podolsky, and Rosen challenge completeness</h3><p>They argued that quantum mechanics might be incomplete. Perhaps, they suggested, separated particles carried definite properties that the theory had not described.</p></div></li><li><span>1964</span><div><h3>John Bell finds an experimental divide</h3><p>Bell found a numerical boundary, now expressed through Bell inequalities. A broad family of theories based on pre-existing local instructions must stay within that boundary; quantum mechanics predicts that suitable experiments can cross it.</p></div></li><li><span>1972 onward</span><div><h3>Clauser, Aspect, Zeilinger, and others test the divide</h3><p>Repeatedly improved experiments crossed Bell’s boundary as quantum mechanics predicted. Later experiments closed important “loopholes”—alternative explanations caused by weaknesses in an experimental setup.</p></div></li><li><span>2022</span><div><Award/><h3>The Nobel Prize in Physics</h3><p>Alain Aspect, John F. Clauser, and Anton Zeilinger received the prize for experiments with entangled photons, Bell-inequality violations, and quantum information science.</p></div></li></ol><small>Historical milestones: Nobel Prize Outreach. Experimental details: the NIST loophole-free Bell-test report. Full links appear in the source drawer.</small></div></section>

    <section className="bell-plain q-shell"><div><FlaskConical/><p className="q-kicker">Bell experiments, in plain language</p><h2>What did they rule out?</h2></div><div><p>Imagine each particle leaves the source with a private instruction sheet containing its answer for every detector setting. Also assume that nothing at Alice’s detector can instantly change Bob’s distant result. Bell showed that theories built from both ideas cannot produce correlations beyond a particular numerical limit.</p><p>Experiments cross that limit. Physicists call the rejected family “local hidden-variable” theories: <i>hidden variables</i> are the imagined instruction sheets, while <i>local</i> means distant events cannot influence one another faster than light. The experiments do not select one universally accepted interpretation of quantum mechanics.</p><aside><Radio/><p><b>No faster-than-light messaging</b>Alice cannot choose her random result to encode a message. Bob must compare his list with hers through a classical channel—an ordinary signal such as a cable, radio link, or message—which cannot travel faster than light.</p></aside></div></section>

    <section className="interdependence-teaching"><div className="q-shell"><div><p className="q-kicker">The Buddhist side</p><h2>Dependent origination<br/>is about conditioned arising.</h2></div><div><p>The early Buddhist formula says that when a relevant condition exists, a dependent process can arise; with the arising of that condition, the process arises. Its reverse describes cessation.</p><p>In its canonical setting, the teaching analyzes the arising of suffering through specific links—such as contact, feeling, craving, and grasping—and the possibility of release when those supports cease.</p><p>It is not a claim about photon polarization, spatial distance, Bell inequalities, or quantum information. “Interdependence” can be a helpful broad translation in some contexts, but it must not erase the teaching’s precise concern with conditions and suffering.</p></div></div></section>

    <section className="dialogue-comparison q-shell"><header><p className="q-kicker">Interactive comparison</p><h2>Two perspectives.<br/>Neither reduced to the other.</h2></header><div className="comparison-columns"><article><span>Buddhist Perspective</span><h3>Dependent origination</h3><dl><div><dt>Domain</dt><dd>Conditioned experience, suffering, and release</dd></div><div><dt>Method</dt><dd>Teaching, ethical practice, contemplation, insight</dd></div><div><dt>Question</dt><dd>How does suffering arise and cease with conditions?</dd></div><div><dt>Evidence</dt><dd>Canonical testimony and contemplative examination</dd></div></dl></article><article><span>Quantum Perspective</span><h3>Entanglement</h3><dl><div><dt>Domain</dt><dd>Prepared quantum systems</dd></div><div><dt>Method</dt><dd>Mathematics, apparatus, repeated measurement, statistics</dd></div><div><dt>Question</dt><dd>Which correlations can physical systems exhibit?</dd></div><div><dt>Evidence</dt><dd>Bell tests and other reproducible experiments</dd></div></dl></article></div><div className="dialogue-lenses reveal-tabs" role="group" aria-label="Reveal comparison details">{(["Similarities","Differences","Misconceptions","Sources","Practice"] as Reveal[]).map(name => <button key={name} aria-pressed={reveal === name} className={reveal === name ? "active" : ""} onClick={() => setReveal(name)}>{name}</button>)}</div><motion.div className="comparison-feature reveal-feature" key={reveal} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><RevealContent reveal={reveal}/></motion.div></section>

    <section className="entanglement-misconceptions"><div className="q-shell"><header><TriangleAlert/><p className="q-kicker">Misconception cards</p><h2>Four claims the evidence<br/>does not support.</h2></header><div><Misconception title="Spiritual communication" text="Bell correlations do not establish telepathy, prayer transmission, or communication between souls."/><Misconception title="Faster-than-light messaging" text="Entanglement cannot be controlled to send usable information faster than light."/><Misconception title="Consciousness connection" text="Standard Bell experiments do not require human consciousness to create or transmit their correlations."/><Misconception title="Universal energy" text="Entanglement is not evidence that all people and objects share a single spiritual energy field."/></div></div></section>

    <section className="entanglement-close q-shell"><article><Eye/><p className="q-kicker">Reflection</p><h2>Does relationship always require physical connection?</h2><p>Before answering, ask what kind of relationship you mean: causal, statistical, social, historical, biological, or contemplative.</p></article><article><CheckCircle2/><p className="q-kicker">Practice · Observe one relationship</p><p>Choose one relationship in your life. Notice what conditions sustain it: time, attention, trust, shared history, boundaries, repair. Change one condition gently and observe what follows.</p><Link href="/practice">Continue in Practice <ArrowRight/></Link></article><article><MessageCircle/><p className="q-kicker">Community discussion</p><p>What becomes clearer when we compare ideas without insisting that they are the same?</p><Link href="/community">Discuss with care <ArrowRight/></Link></article></section>

    <SourceDrawer className="entanglement-sources" subtitle="Nobel records, Bell experiments, and early Buddhist texts" sources={sources} note="The particle interaction is conceptual artwork, not experimental output. A mathematical treatment of states, bases, probabilities, and Bell inequalities belongs in a later advanced layer."/>
  </article>;
}

function Misconception({ title, text }: { title: string; text: string }) { return <MisconceptionPanel icon={TriangleAlert} label="Unsupported claim" title={title}><p>{text}</p></MisconceptionPanel>; }
function RevealContent({ reveal }: { reveal: Reveal }) {
  if (reveal === "Similarities") return <><span>Conceptual resonance</span><h3>Why they appear similar</h3><p>Both challenge a picture made only of isolated, independently describable things. Each gives relationships an important role. This resemblance can begin a thoughtful conversation, but it does not establish identity or scientific proof.</p></>;
  if (reveal === "Differences") return <><span>Different domains and methods</span><h3>Why they are not equivalent</h3><p>Entanglement is a measurable physical phenomenon described by a joint quantum state and tested through statistical experiments. Dependent origination is a Buddhist account of conditioned arising and cessation, especially the arising and ending of suffering.</p></>;
  if (reveal === "Misconceptions") return <><span>Unsupported claims</span><h3>What entanglement does not establish</h3><ul><li>It is not spiritual communication or telepathy.</li><li>It cannot send controllable messages faster than light.</li><li>It does not require or demonstrate a connection between human consciousnesses.</li><li>It does not prove universal consciousness or a universal spiritual energy.</li></ul></>;
  if (reveal === "Sources") return <><span>Evidence trail</span><h3>Read the physics and Buddhist contexts separately</h3><div className="reveal-source-links">{sources.map(source => <a href={source.href} target="_blank" rel="noreferrer" key={source.title}>{source.title}<ExternalLink/></a>)}</div></>;
  return <><span>Practice · Observe one relationship</span><h3>Trace conditions without calling them quantum</h3><p>Choose one relationship in your life. Notice the conditions that sustain it: time, attention, trust, shared history, boundaries, and repair. Change one condition gently and observe what follows.</p><Link href="/practice">Continue in Practice <ArrowRight/></Link></>;
}
function EntanglementArtwork() { return <svg className="entanglement-artwork" viewBox="0 0 1400 860" role="img" aria-label="Two abstract particles separated across a minimal field and joined by correlated wave patterns"><defs><linearGradient id="entangle-bg" x2="1" y2="1"><stop stopColor="#050d18"/><stop offset=".5" stopColor="#12182b"/><stop offset="1" stopColor="#07131d"/></linearGradient><radialGradient id="entangle-a"><stop stopColor="#fff0ad"/><stop offset=".18" stopColor="#d5ac4d"/><stop offset="1" stopColor="#d5ac4d" stopOpacity="0"/></radialGradient><radialGradient id="entangle-b"><stop stopColor="#dce9ff"/><stop offset=".18" stopColor="#7696c1"/><stop offset="1" stopColor="#7696c1" stopOpacity="0"/></radialGradient></defs><rect width="1400" height="860" fill="url(#entangle-bg)"/><circle cx="860" cy="390" r="160" fill="url(#entangle-a)" opacity=".7"/><circle cx="1210" cy="390" r="160" fill="url(#entangle-b)" opacity=".7"/><circle cx="860" cy="390" r="13" fill="#f4d87f"/><circle cx="1210" cy="390" r="13" fill="#b7cbea"/><g fill="none" strokeOpacity=".3"><path d="M860 390C950 220 1120 220 1210 390S1120 560 1035 390S950 220 860 390" stroke="#d5ac4d"/><path d="M860 390C950 560 1120 560 1210 390S1120 220 1035 390S950 560 860 390" stroke="#87a4ca"/></g>{Array.from({ length: 46 }, (_, i) => <circle key={i} cx={690 + (i * 131) % 650} cy={100 + (i * 83) % 650} r={i % 13 === 0 ? 2.2 : .8} fill={i % 3 ? "#cbd5df" : "#d5ac4d"} opacity={.18 + (i % 5) * .1}/>)}</svg>; }
