"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ChevronDown, CircleDot, CloudSun, Dna, Eye, Leaf, MessageCircle, Orbit, Save, Scale, Sparkles } from "lucide-react";
import { DifferencesPanel, OpeningStory, SimilaritiesPanel, SourceDrawer } from "./investigation-system";

const stages = [
  { name: "Nebula", kicker: "Gathering", text: "Gravity draws gas and dust together. A protostar takes shape inside a cloud.", color: "#7d6ea7" },
  { name: "Star", kicker: "Burning", text: "Fusion begins. The star changes slowly throughout its longest stage of life.", color: "#e5bd5e" },
  { name: "Stellar ending", kicker: "Releasing", text: "Its later path depends on mass. Some stars shed material; massive stars can explode and distribute elements.", color: "#db8067" },
  { name: "New worlds", kicker: "Re-forming", text: "Gas, dust, and elements can become part of later stars, planets, and—under rare suitable conditions—living systems.", color: "#75aaa0" },
];

const sources = [
  { kind: "Buddhist text", title: "Dhammapada 277 — Impermanence", publisher: "SuttaCentral · translation by Bhikkhu Sujato", note: "Connects seeing the impermanence of conditioned things with disenchantment toward suffering and the path of practice.", href: "https://suttacentral.net/dhp277/en/sujato" },
  { kind: "Buddhist text", title: "SN 22.45 — Impermanent", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "Applies impermanence to form, feeling, perception, choices, and consciousness, linking insight with non-clinging.", href: "https://suttacentral.net/sn22.45/en/bodhi" },
  { kind: "Astrophysics", title: "Stars: Birth, Life, and Death", publisher: "NASA Science", note: "Describes stellar formation, main-sequence change, endings, and the production and distribution of heavier elements.", href: "https://science.nasa.gov/universe/stars/" },
  { kind: "Aging biology", title: "Does cellular senescence hold secrets for healthier aging?", publisher: "National Institute on Aging", note: "Explains how cells can become senescent and how biological aging involves changing tissues and cellular processes.", href: "https://www.nia.nih.gov/news/does-cellular-senescence-hold-secrets-healthier-aging" },
  { kind: "Climate science", title: "The Effects of Climate Change", publisher: "NASA Science", note: "Summarizes observed and projected changes in climate systems and their effects.", href: "https://science.nasa.gov/climate-change/effects/" },
  { kind: "Evolution", title: "Introduction to Human Evolution", publisher: "Smithsonian Human Origins Program", note: "Explains evolution as biological change in populations over generations and places humans within that history.", href: "https://humanorigins.si.edu/education/introduction-human-evolution" },
];

export function ImpermanenceInvestigation() {
  const [stage, setStage] = useState(0);
  const [journal, setJournal] = useState("");
  const [saved, setSaved] = useState(false);

  const saveJournal = () => {
    localStorage.setItem("qunara-impermanence-reflection", journal);
    setSaved(true);
  };

  return <article className="impermanence-investigation" id="impermanence">
    <header className="impermanence-opening">
      <ImpermanenceArtwork/>
      <div className="impermanence-wash"/>
      <div className="q-shell"><p className="q-kicker">Investigation 03 · Ancient observations, modern echoes</p><h1>Impermanence<br/><em>Everything Changes.</em></h1><p>A star gathers from darkness. It burns, changes, and ends. Its material may enter new worlds. Much later, on one such world, a leaf opens—and a person raises a hand made from ancient elements toward the night.</p><a href="#changing-story">Follow the change <ChevronDown/></a></div>
    </header>

    <OpeningStory className="impermanence-story q-shell" id="changing-story" kicker="A story without a still frame" title="The star was never only one thing."><p>Before it shone, it was a gathering cloud. During its life, its temperature, brightness, fuel, and balance changed. Its ending did not erase every part of its story.</p><p>Elements made or dispersed by generations of stars became ingredients in later cosmic structures. Some entered planets. On Earth, elements move through air, stone, water, cells, trees, and bodies. The path is branching, not a single chain guaranteed to lead from one star to one person.</p><p>Buddhist teaching begins closer to home: this body changes; pleasant feeling changes; grief changes; every experience assembled from conditions changes. Anicca is not merely a fact to memorize. It is something to notice before we demand that a changing thing remain.</p></OpeningStory>

    <section className="anicca-teaching"><div className="q-shell"><div><EvidenceLabel label="Buddhist teaching" value="Direct textual basis" tone="strong"/><p className="q-kicker">What is Anicca?</p><h2>Not simply “everything ends.”</h2></div><div><p><i>Anicca</i> is commonly translated as impermanence or inconstancy. Conditioned experiences arise because supporting conditions come together. When those conditions shift, the experience cannot stay exactly as it was.</p><p>Early Buddhist teachings apply this observation to the parts of lived experience: body, feeling, perception, mental activities, and consciousness. The practical question is not whether change exists, but what happens when we cling to what cannot remain under our control.</p><p>The Buddha taught impermanence as a way of seeing more clearly. When changing experience is treated as permanently “mine,” its movement brings friction and distress. Seeing it accurately can loosen grasping; it is not a command to become cold, passive, or indifferent.</p></div></div></section>

    <section className="lifecycle q-shell"><header><p className="q-kicker">Animated lifecycle</p><h2>A star changes<br/>at every scale of time.</h2><p>Choose a stage. This simplified illustration shows broad stellar pathways; a star’s actual evolution depends strongly on its mass and composition.</p></header><div className="lifecycle-stage"><div className="stellar-orbit" style={{ "--stage-color": stages[stage].color } as React.CSSProperties}><motion.i key={stage} initial={{ scale: .45, opacity: .2 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: .7 }}/><motion.i key={`ring-${stage}`} initial={{ rotate: 0, scale: .7 }} animate={{ rotate: 180, scale: 1 }} transition={{ duration: 1.2 }}/><span>{stage + 1}</span></div><motion.article key={stage} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }}><span>{stages[stage].kicker}</span><h3>{stages[stage].name}</h3><p>{stages[stage].text}</p></motion.article></div><div className="lifecycle-controls" role="group" aria-label="Stellar lifecycle">{stages.map((item, index) => <button key={item.name} aria-pressed={stage === index} className={stage === index ? "active" : ""} onClick={() => setStage(index)}><span>0{index + 1}</span>{item.name}</button>)}</div></section>

    <section className="change-timeline"><div className="q-shell"><header><p className="q-kicker">Modern science</p><h2>Change is not one process.</h2><p>Science investigates different kinds of change through different methods, timescales, and evidence.</p></header><ol><ChangeItem icon={Orbit} scale="Cosmic" title="Stars evolve" text="Stars form, spend long periods fusing light elements into heavier ones, and meet different endings depending largely on their mass."/><ChangeItem icon={CircleDot} scale="Cellular" title="Cells change" text="Cells grow, divide, take on specialized jobs, respond to stress, grow old, or die. Scientists call a cell that has stopped dividing but remains active senescent."/><ChangeItem icon={Eye} scale="A lifetime" title="Bodies age" text="Aging is not one clock. It emerges from changes in cells, tissues, organs, repair systems, behavior, and environment."/><ChangeItem icon={CloudSun} scale="Planetary" title="Climate changes" text="Climate changes naturally over long periods. Measurements show that today’s rapid warming is driven mainly by greenhouse gases released through human activity."/><ChangeItem icon={Dna} scale="Generations" title="Species evolve" text="Populations change across generations. Mutations introduce genetic differences; natural selection favors some inherited traits; chance can shift traits in small populations; and migration carries genes between populations."/></ol><small>Source trail: NASA Science for stars and climate; the National Institute on Aging for cell aging; the Smithsonian Human Origins Program for evolution. Full links appear below.</small></div></section>

    <section className="impermanence-comparison q-shell"><header><p className="q-kicker">Similarity and difference</p><h2>One word.<br/>Two kinds of inquiry.</h2></header><div><SimilaritiesPanel icon={CheckCircle2} label="Where they meet" title="Stable appearance can hide continuing change."><p>A star, body, forest, or mood may seem steady at one timescale while processes continue within it. Both perspectives challenge the intuition that familiar things are fixed.</p></SimilaritiesPanel><DifferencesPanel icon={Scale} label="Where they part" title="Science explains processes. Buddhism examines clinging."><p>Science investigates how physical and biological systems change and tests explanations against evidence. Buddhist practice studies the distress that arises when changing experience is grasped as permanent, controllable, or self.</p></DifferencesPanel></div><aside><b>Not scientifically equivalent</b><p>Scientific evidence for stellar evolution, aging, climate change, or biological evolution does not prove the Buddhist path. Anicca is a contemplative teaching with ethical and liberative aims, not a replacement for physical theory.</p></aside></section>

    <section className="impermanence-journal"><div className="q-shell"><div><Sparkles/><p className="q-kicker">Reflection journal</p><h2>What are you asking<br/>to remain unchanged?</h2><p>Write privately. Your entry stays in this browser and is not shared with the community.</p></div><div className="journal-card"><label htmlFor="impermanence-entry">A person, feeling, season, role, or hope I am holding tightly…</label><textarea id="impermanence-entry" value={journal} onChange={event => { setJournal(event.target.value); setSaved(false); }} placeholder="Write without trying to solve it…"/><button onClick={saveJournal} disabled={!journal.trim()}><Save/>{saved ? "Saved privately" : "Save private entry"}</button></div></div></section>

    <section className="impermanence-practice q-shell"><article><Leaf/><p className="q-kicker">Practice · Five changing things</p><h2>Observe five changes today.</h2><ol><li>Light moving across a room.</li><li>A sound appearing and fading.</li><li>A sensation in the body.</li><li>A feeling changing intensity.</li><li>A living thing responding to its surroundings.</li></ol><p>Name only what you observe. Notice any wish for the pleasant to stay or the unpleasant to disappear.</p><Link href="/practice">Continue in Practice <ArrowRight/></Link></article><article><MessageCircle/><p className="q-kicker">Community discussion</p><h2>What have you learned from impermanence?</h2><p>Share an experience without turning another person’s loss into a lesson for them. Reflection deserves gentleness as well as honesty.</p><Link href="/community">Discuss with care <ArrowRight/></Link></article></section>

    <SourceDrawer className="impermanence-sources" subtitle="Early Buddhist translations and authoritative science references" sources={sources} note="The star-to-human opening is poetic compression. Matter circulates through complex, branching physical and biological histories; it is not a claim that material from one depicted star followed this exact sequence."/>
  </article>;
}

function ChangeItem({ icon: Icon, scale, title, text }: { icon: typeof Orbit; scale: string; title: string; text: string }) { return <motion.li initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .4 }}><span>{scale}</span><Icon/><div><h3>{title}</h3><p>{text}</p></div></motion.li>; }
function EvidenceLabel({ label, value, tone }: { label: string; value: string; tone: "strong" }) { return <div className={`evidence-pill ${tone}`}><div><span>{label}</span><b>{value}</b></div></div>; }

function ImpermanenceArtwork() { return <svg className="impermanence-artwork" viewBox="0 0 1400 840" role="img" aria-label="A star transforming into scattered elements, a planet, a tree, and a human silhouette"><defs><radialGradient id="change-star"><stop stopColor="#fff2b8"/><stop offset=".18" stopColor="#d9a84f"/><stop offset=".55" stopColor="#9b574e" stopOpacity=".45"/><stop offset="1" stopColor="#07111d" stopOpacity="0"/></radialGradient><linearGradient id="change-bg" x2="1" y2="1"><stop stopColor="#07111d"/><stop offset=".55" stopColor="#1c2238"/><stop offset="1" stopColor="#0b1d27"/></linearGradient></defs><rect width="1400" height="840" fill="url(#change-bg)"/><circle cx="930" cy="285" r="240" fill="url(#change-star)"/><circle cx="930" cy="285" r="38" fill="#f3d988"/>{Array.from({ length: 54 }, (_, i) => <circle key={i} cx={650 + (i * 113) % 680} cy={90 + (i * 71) % 600} r={i % 11 === 0 ? 3 : 1} fill={i % 4 ? "#c8d4dc" : "#dcb75c"} opacity={.2 + (i % 5) * .13}/>) }<path d="M880 550q120-90 250 0q-100 190-250 0z" fill="#4d7a74" fillOpacity=".35" stroke="#8db5a5" strokeOpacity=".4"/><path d="M1110 670q35-100 5-180m0 75q-45-45-82-29m83-5q39-46 78-35m-80 105q-30-35-64-22m65-20q32-39 65-27" fill="none" stroke="#9ab78c" strokeWidth="5" strokeLinecap="round"/><circle cx="1115" cy="462" r="7" fill="#d9b45b"/><path d="M1255 425q-17 35 0 70v88m0-88q-35 32-45 70m45-70q35 32 45 70m-45 18l-35 90m35-90l35 90" fill="none" stroke="#b7cac7" strokeWidth="5" strokeLinecap="round"/><circle cx="1255" cy="402" r="18" fill="none" stroke="#b7cac7" strokeWidth="4"/></svg>; }
