"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ChevronDown, CircleDot, Eye, FlaskConical, Gauge, MessageCircle, RefreshCw, Sparkles, TriangleAlert, Waves } from "lucide-react";
import { MisconceptionPanel, OpeningStory, SourceDrawer } from "./investigation-system";

const steps = [
  { name: "Wave", title: "Describe the state", text: "A wave function is a mathematical object used to represent a quantum state and predict measurement probabilities." },
  { name: "Possibilities", title: "Combine possible outcomes", text: "A superposition gives each alternative an amplitude, a number with both size and phase. Phase works a little like timing between waves: alternatives can reinforce or cancel one another. This is more than a list of unknown options." },
  { name: "Measurement", title: "Ask a physical question", text: "A measurement couples the system to an apparatus in a chosen basis. Quantum theory gives probabilities for the possible recorded results." },
  { name: "Outcome", title: "Record one result", text: "A single trial produces a definite recorded outcome. Repeating the same preparation many times reveals the probability pattern." },
];

const sources = [
  { kind: "Quantum physics", title: "Quantum Computing Explained", publisher: "National Institute of Standards and Technology", note: "Introduces superposition, disturbance, measurement, and quantum-computing applications in accessible language.", href: "https://www.nist.gov/quantum-information-science/quantum-computing-explained" },
  { kind: "Quantum learning", title: "Superposition with Qiskit", publisher: "IBM Quantum Learning", note: "Explains amplitudes, phase, interference, and why a superposition differs from ordinary classical probability.", href: "https://quantum.cloud.ibm.com/learning/en/modules/quantum-mechanics/superposition-with-qiskit" },
  { kind: "Quantum learning", title: "Quantum mechanics basics", publisher: "IBM Quantum Learning", note: "Introduces measurement probabilities, measurement bases, and post-measurement states.", href: "https://quantum.cloud.ibm.com/learning/en/courses/use-a-qc-today/quantum-mechanics-basics" },
  { kind: "Early Buddhist text", title: "SN 12.15 — Kaccānagotta", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "Avoids the opposed extremes of existence and nonexistence through dependent origination; it is not a statement about quantum alternatives.", href: "https://suttacentral.net/sn12.15/en/bodhi" },
  { kind: "Mahāyāna Buddhist text", title: "The Heart Sūtra — Toh 21", publisher: "84000: Translating the Words of the Buddha", note: "A canonical Mahāyāna source for form-and-emptiness language, presented within a distinct philosophical and contemplative tradition.", href: "https://84000.co/translation/toh21" },
];

export function SuperpositionDialogue() {
  const [step, setStep] = useState(0);
  const [outcome, setOutcome] = useState<0 | 1>(0);
  const [focus, setFocus] = useState<"Shared language" | "Physics" | "Non-duality" | "Boundary">("Shared language");

  const advance = () => {
    if (step === 3) { setStep(0); return; }
    const next = step + 1;
    if (next === 3) setOutcome(current => current === 0 ? 1 : 0);
    setStep(next);
  };

  return <article className="superposition-dialogue" id="superposition-dialogue">
    <header className="superposition-opening"><SuperpositionArtwork/><div className="superposition-wash"/><div className="q-shell"><p className="q-kicker">Quantum Dialogue · Investigation 02</p><h1>Superposition<br/><em>and Non-Dual Thinking.</em></h1><p>A musician touches one string. Two waves travel, overlap, and reshape the sound. Quantum superposition also uses a language of combination and interference—but it is a precise mathematical structure, not a metaphor for holding two opinions.</p><a href="#superposition-story">Follow the possibilities <ChevronDown/></a></div></header>

    <OpeningStory className="superposition-story q-shell" id="superposition-story" kicker="A story before equations" title={<>The unopened path<br/>is not yet an outcome.</>}><p>Imagine a carefully prepared quantum system with two possible measurement results. Before measurement, quantum theory represents its state as a superposition of the alternatives.</p><p>This does not mean a tiny ordinary object is secretly sitting in two familiar boxes in the everyday sense. Nor does it mean scientists simply lack information about a result already decided. The alternatives have amplitudes and phases that can interfere—a behavior ordinary uncertainty cannot reproduce.</p><p>When an apparatus performs a measurement, one result is recorded in that trial. Prepare and measure the system many times, and a probability pattern emerges.</p></OpeningStory>

    <section className="wavefunction-explainer"><div className="q-shell"><div><p className="q-kicker">The wave function</p><h2>A tool for predicting<br/>possible outcomes.</h2></div><div><p>The wave function is a mathematical description of a quantum state. Think of it as a prediction tool: it assigns an amplitude to each result an experiment could record.</p><p>An amplitude is not an ordinary probability. It carries a size and a phase. Like waves arriving in step or out of step, amplitudes can reinforce or cancel through <i>interference</i>. Physicists calculate outcome probabilities from these amplitudes.</p><p>Physicists disagree about what the wave function ultimately says about reality. They agree on the mathematical rules used to make predictions that experiments can test.</p></div></div></section>

    <section className="superposition-lab q-shell"><header><p className="q-kicker">Interactive animation</p><h2>Wave → possibilities →<br/>measurement → outcome.</h2><p>This is a conceptual sequence, not a numerical quantum simulation. The alternating demonstration outcomes are not generated with quantum randomness.</p></header><div className="superposition-stage"><div className={`possibility-field stage-${step}`}><motion.div className="quantum-wave" animate={{ opacity: step === 0 ? 1 : .38 }}><i/><i/><i/></motion.div><motion.div className="possible-path path-zero" animate={{ x: step >= 1 ? -115 : 0, y: step >= 1 ? -75 : 0, opacity: step === 3 && outcome !== 0 ? .1 : step >= 1 ? 1 : 0 }}><span>0</span></motion.div><motion.div className="possible-path path-one" animate={{ x: step >= 1 ? 115 : 0, y: step >= 1 ? 75 : 0, opacity: step === 3 && outcome !== 1 ? .1 : step >= 1 ? 1 : 0 }}><span>1</span></motion.div>{step >= 2 && <motion.div className="measurement-gate" initial={{ opacity: 0, scale: .7 }} animate={{ opacity: 1, scale: 1 }}><Gauge/><span>Measure</span></motion.div>}{step === 3 && <motion.div className="recorded-outcome" initial={{ opacity: 0, scale: .6 }} animate={{ opacity: 1, scale: 1 }}>Outcome {outcome}</motion.div>}</div><motion.article key={step} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><span>0{step + 1} · {steps[step].name}</span><h3>{steps[step].title}</h3><p>{steps[step].text}</p><button onClick={advance}>{step === 3 ? <><RefreshCw/>Reset sequence</> : <>{step === 2 ? "Reveal illustrative outcome" : "Continue"}<ArrowRight/></>}</button></motion.article></div><nav className="superposition-steps" aria-label="Superposition sequence">{steps.map((item, index) => <button key={item.name} className={step === index ? "active" : ""} onClick={() => setStep(index)}><span>0{index + 1}</span>{item.name}</button>)}</nav></section>

    <section className="measurement-context"><div className="q-shell"><article><FlaskConical/><span>Preparation</span><h3>Make the same state again.</h3><p>A probability claim is tested across repeated preparations and measurements, not established by one dramatic result.</p></article><article><Waves/><span>Interference</span><h3>Phase makes superposition distinct.</h3><p>Alternative amplitudes can combine constructively or destructively. This is why a quantum state is not merely a hidden classical coin toss.</p></article><article><Eye/><span>Measurement</span><h3>The apparatus matters.</h3><p>The chosen measurement basis determines which set of possible outcomes the experiment asks about. “Observation” means a physical measurement process, not necessarily a conscious person watching.</p></article></div></section>

    <section className="nondual-teaching q-shell"><header><p className="q-kicker">The Buddhist side</p><h2>Non-duality is not<br/>one single doctrine.</h2></header><div><p>Different Buddhist traditions use non-dual language differently. In SN 12.15, an early discourse avoids the fixed extremes “everything exists” and “nothing exists,” teaching conditioned arising as a middle. This is not the claim that both extremes exist simultaneously.</p><p>Later Mahāyāna traditions use teachings on emptiness to challenge rigid separation between categories such as form and emptiness. The Heart Sūtra is a famous example. Its purpose concerns wisdom, attachment, and liberation—not laboratory predictions.</p><p>Contemplative non-duality can question the habitual division of experience into a permanent observer standing apart from an observed world. That inquiry belongs to philosophy and practice. It is not a wave function.</p></div></section>

    <section className="superposition-comparison q-shell"><header><p className="q-kicker">Interactive comparison</p><h2>Similar imagery.<br/>Different work.</h2></header><div className="superposition-focus" role="group" aria-label="Comparison focus">{(["Shared language", "Physics", "Non-duality", "Boundary"] as const).map(item => <button key={item} aria-pressed={focus === item} className={focus === item ? "active" : ""} onClick={() => setFocus(item)}>{item}</button>)}</div><div className={`superposition-columns focus-${focus.toLowerCase().replace(" ", "-")}`}><article><CircleDot/><span>Quantum mechanics</span><h3>Superposition</h3><p>A linear mathematical combination of quantum states, with amplitudes and phases that determine interference and measurement probabilities.</p><dl><div><dt>Tested through</dt><dd>Controlled physical experiments</dd></div><div><dt>Changes through</dt><dd>Evolution, interaction, decoherence, measurement</dd></div><div><dt>Produces</dt><dd>Statistical predictions for outcomes</dd></div></dl></article><article><Sparkles/><span>Contemplative philosophy</span><h3>Non-dual thinking</h3><p>A family of philosophical and contemplative approaches that question rigid oppositions, intrinsic separation, or fixed conceptual extremes.</p><dl><div><dt>Explored through</dt><dd>Texts, reasoning, ethics, contemplation</dd></div><div><dt>Changes through</dt><dd>Insight into habits of perception and clinging</dd></div><div><dt>Aims toward</dt><dd>Wisdom and freedom from suffering</dd></div></dl></article></div><aside><TriangleAlert/><p><b>Meditation does not create quantum superposition.</b>Meditation can alter attention, emotion, and reported experience. It does not prepare a brain, body, or everyday object in the controlled coherent quantum state meant by laboratory superposition.</p></aside></section>

    <section className="superposition-misconceptions"><div className="q-shell"><header><p className="q-kicker">Misconceptions</p><h2>What superposition<br/>does not mean.</h2></header><div><Miscon title="“Everything is literally all possibilities.”" text="A superposition is defined relative to a quantum state space and measurement basis, not an unrestricted catalogue of every imaginable event."/><Miscon title="“It is just ordinary uncertainty.”" text="Quantum amplitudes carry phase and interfere. A classical unknown outcome does not generally behave this way."/><Miscon title="“A mind chooses physical reality.”" text="Quantum measurement does not establish that human awareness selects the universe or controls arbitrary outcomes."/><Miscon title="“Non-duality predicted quantum theory.”" text="Resonant language does not supply the mathematics, apparatus, or experimental evidence of quantum mechanics."/></div></div></section>

    <section className="superposition-close q-shell"><article><Eye/><p className="q-kicker">Reflection</p><h2>When does a useful distinction become a rigid division?</h2><p>Consider a distinction you need—and one you may be treating as absolute.</p></article><article><CheckCircle2/><p className="q-kicker">Practice · Notice before naming</p><p>Listen to a sound for one minute. Notice the raw changing experience, then the labels the mind adds: pleasant, distant, mine, interruption. The exercise explores perception, not quantum physics.</p><Link href="/practice">Continue in Practice <ArrowRight/></Link></article><article><MessageCircle/><p className="q-kicker">Community discussion</p><p>Can two ideas illuminate one another while remaining fundamentally different?</p><Link href="/community">Discuss with care <ArrowRight/></Link></article></section>

    <SourceDrawer className="superposition-sources" subtitle="Quantum learning resources and distinct Buddhist textual contexts" sources={sources} note="Interpretations of measurement and of Buddhist non-duality are internally diverse. This investigation introduces distinctions without claiming one final interpretation for either field."/>
  </article>;
}

function Miscon({ title, text }: { title: string; text: string }) { return <MisconceptionPanel icon={TriangleAlert} label="Not supported" title={title}><p>{text}</p></MisconceptionPanel>; }
function SuperpositionArtwork() { return <svg className="superposition-artwork" viewBox="0 0 1400 880" role="img" aria-label="Abstract waves divide into glowing possibilities, pass through a measurement plane, and resolve into one outcome"><defs><linearGradient id="super-bg" x2="1" y2="1"><stop stopColor="#060d17"/><stop offset=".5" stopColor="#19203a"/><stop offset="1" stopColor="#091923"/></linearGradient><radialGradient id="super-glow"><stop stopColor="#bca8df" stopOpacity=".55"/><stop offset="1" stopColor="#7867a8" stopOpacity="0"/></radialGradient></defs><rect width="1400" height="880" fill="url(#super-bg)"/><ellipse cx="1050" cy="410" rx="380" ry="330" fill="url(#super-glow)"/><g fill="none"><path d="M650 440q90-190 180 0t180 0t180 0" stroke="#d5ac4d" strokeOpacity=".5"/><path d="M650 440q90 190 180 0t180 0t180 0" stroke="#8da7d1" strokeOpacity=".5"/><path d="M650 440q70-95 140 0t140 0t140 0t140 0" stroke="#b69bd6" strokeOpacity=".35"/></g><path d="M1090 170v540" stroke="#e7e5df" strokeOpacity=".2" strokeDasharray="5 9"/><circle cx="1210" cy="440" r="14" fill="#e7c565"/><circle cx="1210" cy="440" r="75" fill="none" stroke="#e7c565" strokeOpacity=".25"/>{Array.from({ length: 42 }, (_, i) => <circle key={i} cx={650 + (i * 127) % 650} cy={100 + (i * 89) % 650} r={i % 11 === 0 ? 2.3 : .8} fill={i % 3 ? "#d8e0e8" : "#d5ac4d"} opacity={.18 + (i % 5) * .11}/>)}</svg>; }
