"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ChevronDown, CircleDot, Eye, FlaskConical, MessageCircle, Network, Scale, TriangleAlert, Waves } from "lucide-react";
import { MisconceptionPanel, OpeningStory, SourceDrawer } from "./investigation-system";

const sources = [
  { kind: "Buddhist translation", title: "The Heart Sūtra — Toh 21", publisher: "84000: Translating the Words of the Buddha", note: "A canonical Mahāyāna source for the relation of form and emptiness within the perfection-of-wisdom tradition.", href: "https://84000.co/translation/toh21" },
  { kind: "Buddhist translation context", title: "The Sūtra on Transmigration Through Existences — Toh 226", publisher: "84000: Translating the Words of the Buddha", note: "Its translation glossary explains emptiness as absence of inherent existence and self-identity, not denial of dependent conventional phenomena.", href: "https://84000.co/translation/toh226" },
  { kind: "Early Buddhist context", title: "SN 12.15 — Kaccānagotta", publisher: "SuttaCentral · translation by Bhikkhu Bodhi", note: "Avoids the extremes that everything exists and that nothing exists, teaching through dependent arising.", href: "https://suttacentral.net/sn12.15/en/bodhi" },
  { kind: "Quantum field theory", title: "Building a tower out of the vacuum", publisher: "APS Physics", note: "States the particle-physics use of vacuum as the ground state of a theory and distinguishes metastable from lower-energy vacuum states.", href: "https://physics.aps.org/articles/v2/s11" },
  { kind: "Physics context", title: "The Vacuum: Is Empty Space Really Empty?", publisher: "Fermilab · Connecting Quarks with the Cosmos", note: "Explains that a field's lowest-energy state need not have zero field value or zero energy and can have measurable physical consequences.", href: "https://www.fnal.gov/pub/max/pdfs/Connecting%20Quarks%20with%20the%20Cosmos.pdf" },
];

export function VacuumDialogue() {
  const [diagram, setDiagram] = useState<"Emptiness" | "Vacuum">("Emptiness");

  return <article className="vacuum-dialogue" id="vacuum-dialogue">
    <header className="vacuum-opening"><VacuumArtwork/><div className="vacuum-wash"/><div className="q-shell"><p className="q-kicker">Quantum Dialogue · Investigation 03</p><h1>Śūnyatā<br/><em>and the Quantum Vacuum.</em></h1><p>A bowl is empty of water but full of air, history, clay, labor, and use. A laboratory vacuum is empty of ordinary particles by a chosen definition, yet remains a physical state. The shared word “empty” conceals two very different teachings.</p><a href="#emptiness-teaching">Begin with the bowl <ChevronDown/></a></div></header>

    <OpeningStory className="vacuum-story q-shell" id="emptiness-teaching" kicker="A story of an ordinary cup" title="Empty of what?"><p>A potter places a cup on the table. We call it one thing. Look closer and the unity loosens: clay, heat, hands, transport, language, expectation, and a purpose supplied by the person who reaches for it.</p><p>If the handle breaks, is it still the same cup? If the clay is ground down and shaped again, where did the cup go? Emptiness asks us to inspect the independent essence we assumed was hiding inside.</p><p>The answer is not that the cup does not exist. It holds tea, can be repaired, and can cut a hand when broken. It exists conventionally through parts, conditions, designation, and use—without possessing a permanent, self-established “cup nature.”</p></OpeningStory>

    <section className="emptiness-teaching"><div className="q-shell"><div><p className="q-kicker">What Śūnyatā teaches</p><h2>Empty of independent<br/>and intrinsic existence.</h2></div><div><p><i>Śūnyatā</i>, usually translated as emptiness, is developed in multiple Buddhist traditions with different vocabularies and arguments. In Mahāyāna philosophy, phenomena are empty of an inherent nature that establishes itself independently.</p><p>Things still function. Causes have consequences. People experience pain and care. Conventional distinctions remain usable. Emptiness challenges the belief that these changing, conditioned realities possess a fixed core existing from their own side.</p><p>Dependent existence and emptiness therefore support one another: because a phenomenon arises through conditions, it is empty of isolated self-existence; because it is not frozen by an intrinsic essence, it can arise, change, relate, and cease.</p><aside><CheckCircle2/><p><b>Emptiness is not nihilism.</b> “Nothing exists, nothing matters” is precisely the kind of extreme Buddhist middle-way reasoning rejects. Ethical responsibility is not erased by dependence.</p></aside></div></div></section>

    <section className="emptiness-diagram q-shell"><header><p className="q-kicker">Conceptual diagram 01</p><h2>The cup exists<br/>through conditions.</h2></header><div className="cup-network"><svg viewBox="0 0 800 590" aria-hidden="true">{[[400,295,110,100],[400,295,690,100],[400,295,100,300],[400,295,700,300],[400,295,150,500],[400,295,650,500]].map((line,index)=><motion.line key={index} x1={line[0]} y1={line[1]} x2={line[2]} y2={line[3]} stroke="#d5ac4d" initial={{pathLength:0,opacity:0}} whileInView={{pathLength:1,opacity:.35}} viewport={{once:true}} transition={{delay:index*.08}}/>)}</svg><div className="cup-center"><i/><span>Cup</span><small>No isolated essence found</small></div>{["Clay","Potter","Kiln","Language","Use","Community"].map((item,index)=><motion.span key={item} className={`cup-condition c${index}`} initial={{opacity:0,scale:.7}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:.1+index*.07}}>{item}</motion.span>)}</div><p>Removing a condition changes what the cup can be, how it appears, or whether the category applies. The diagram is a teaching aid, not a complete philosophical proof.</p></section>

    <section className="quantum-vacuum-teaching"><div className="q-shell"><div><FlaskConical/><p className="q-kicker">What physics means by vacuum</p><h2>The lowest-energy state<br/>of a quantum field.</h2></div><div><p>In quantum field theory, particles are understood as excitations of fields. The vacuum is the ground state: the state with the lowest available energy for the theory or system under consideration.</p><p>“Lowest” does not automatically mean zero. A field can have nonzero vacuum values, correlations, and fluctuations, and vacuum structure can affect measurable phenomena. The exact description depends on the theory, observer, boundaries, and physical setting.</p><p>Popular accounts often picture virtual particles literally appearing and disappearing. Virtual particles are primarily elements in perturbative calculations, not tiny objects directly photographed inside empty space. The underlying vacuum effects are physical; the cartoon should not replace the formalism.</p></div></div></section>

    <section className="vacuum-diagram q-shell"><header><p className="q-kicker">Conceptual diagram 02</p><h2>Lowest energy<br/>does not mean nothing.</h2></header><div className="energy-field"><div className="energy-levels"><span>Excited field state</span><i/><span>Particle excitation</span><i/><span>Lowest available energy</span><i className="ground"/><b>Quantum vacuum</b></div><div className="field-ground"><Waves/><svg viewBox="0 0 600 220" aria-hidden="true"><motion.path d="M0 110Q50 45 100 110T200 110T300 110T400 110T500 110T600 110" fill="none" stroke="#8fa8d0" animate={{pathLength:[0,1],opacity:[.2,.7]}} transition={{duration:2,repeat:Infinity,repeatType:"reverse"}}/><path d="M0 110h600" stroke="#d5ac4d" strokeOpacity=".35" strokeDasharray="5 8"/></svg><p>Ground-state fluctuations and correlations belong to a mathematical physical theory. This wave is conceptual artwork, not measured vacuum data.</p></div></div></section>

    <section className="vacuum-comparison q-shell"><header><p className="q-kicker">Interactive comparison</p><h2>Choose the meaning<br/>of “empty.”</h2></header><div className="vacuum-toggle" role="group" aria-label="Emptiness comparison"><button aria-pressed={diagram==="Emptiness"} className={diagram==="Emptiness"?"active":""} onClick={()=>setDiagram("Emptiness")}><Network/>Buddhist emptiness</button><button aria-pressed={diagram==="Vacuum"} className={diagram==="Vacuum"?"active":""} onClick={()=>setDiagram("Vacuum")}><CircleDot/>Quantum vacuum</button></div><motion.article key={diagram} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}}>{diagram==="Emptiness"?<><Network/><span>Śūnyatā</span><h3>Empty of independent intrinsic nature</h3><p>A philosophical and contemplative analysis of how phenomena exist dependently, conventionally, and without self-established essence.</p><dl><div><dt>Domain</dt><dd>Phenomena, experience, concepts, suffering</dd></div><div><dt>Method</dt><dd>Reasoning, textual study, ethics, contemplation</dd></div><div><dt>Aim</dt><dd>Wisdom and release from reification and clinging</dd></div></dl></>:<><CircleDot/><span>Quantum field theory</span><h3>The ground state of a physical theory</h3><p>A mathematically defined physical state with the lowest available energy and field-specific properties.</p><dl><div><dt>Domain</dt><dd>Quantum fields and physical systems</dd></div><div><dt>Method</dt><dd>Mathematics, experiments, measurement</dd></div><div><dt>Aim</dt><dd>Predict and explain physical phenomena</dd></div></dl></>}</motion.article></section>

    <section className="vacuum-warning"><div className="q-shell"><TriangleAlert/><p className="q-kicker">The boundary cannot be optional</p><h2>Quantum vacuum<br/><span>≠</span><br/>Śūnyatā.</h2><div><p>The quantum vacuum is not the Buddhist meaning of emptiness made measurable. It is a particular state defined within quantum field theory.</p><p>Śūnyatā is not a hidden substance, cosmic field, reservoir of energy, or physical space from which particles emerge. It is not located between atoms.</p><p>Vacuum experiments cannot prove Buddhist liberation, and meditation does not manipulate vacuum energy. Similar English words do not establish scientific equivalence.</p></div><aside><Scale/><b>Conceptual resonance: limited</b><span>Scientific equivalence: none established</span></aside></div></section>

    <section className="vacuum-misconceptions q-shell"><header><p className="q-kicker">Four corrections</p><h2>Neither nothingness<br/>nor universal substance.</h2></header><div><Correction title="“Emptiness means nothing exists.”" text="Buddhist analysis preserves conventional functioning and consequences while denying independent intrinsic essence."/><Correction title="“The vacuum is literal nothing.”" text="Physics defines it as a physical ground state with theory-dependent structure and properties."/><Correction title="“Both are the same cosmic field.”" text="Śūnyatā is not matter, energy, space, or a field. The quantum vacuum is not a contemplative realization."/><Correction title="“Vacuum fluctuations prove ancient wisdom.”" text="A physical result does not establish that a Buddhist philosophical term predicted quantum field theory."/></div></section>

    <section className="vacuum-close q-shell"><article><Eye/><p className="q-kicker">Reflection</p><h2>Can something be empty of independent existence without being nonexistent?</h2><p>Choose one ordinary thing. Trace its parts, causes, name, users, and setting. What remains when you stop searching for an isolated essence?</p></article><article><CheckCircle2/><p className="q-kicker">Practice · Hold without freezing</p><p>Notice one label you use today—success, failure, stranger, self. Ask which conditions make the label useful and where treating it as permanent causes harm.</p><Link href="/practice">Continue in Practice <ArrowRight/></Link></article><article><MessageCircle/><p className="q-kicker">Community discussion</p><p>How can emptiness support responsibility rather than weaken it?</p><Link href="/community">Discuss with care <ArrowRight/></Link></article></section>

    <SourceDrawer className="vacuum-sources" subtitle="Buddhist translation contexts and quantum-vacuum physics" sources={sources} note="Both emptiness philosophy and quantum-vacuum physics contain multiple schools, technical subtleties, and active debates. The diagrams introduce concepts; they do not replace specialist texts or equations."/>
  </article>;
}

function Correction({title,text}:{title:string;text:string}){return <MisconceptionPanel icon={TriangleAlert} title={title}><p>{text}</p></MisconceptionPanel>}
function VacuumArtwork(){return <svg className="vacuum-artwork" viewBox="0 0 1400 880" role="img" aria-label="A ceramic bowl dissolves into a network of conditions beside a minimal quantum field ground state"><defs><linearGradient id="vac-bg" x2="1" y2="1"><stop stopColor="#070e17"/><stop offset=".5" stopColor="#15252c"/><stop offset="1" stopColor="#16172a"/></linearGradient><radialGradient id="vac-glow"><stop stopColor="#7d9f9d" stopOpacity=".4"/><stop offset="1" stopColor="#7d9f9d" stopOpacity="0"/></radialGradient></defs><rect width="1400" height="880" fill="url(#vac-bg)"/><ellipse cx="1030" cy="410" rx="420" ry="350" fill="url(#vac-glow)"/><path d="M775 320q150 90 300 0q-15 230-150 230T775 320z" fill="#9bb5ae" fillOpacity=".12" stroke="#b9cbc5" strokeOpacity=".4"/><ellipse cx="925" cy="320" rx="150" ry="45" fill="#07111c" stroke="#d5ac4d" strokeOpacity=".45"/><g stroke="#d5ac4d" strokeOpacity=".18">{Array.from({length:24},(_,i)=><line key={i} x1="925" y1="320" x2={650+(i*119)%680} y2={100+(i*83)%650}/>)}</g>{Array.from({length:34},(_,i)=><circle key={i} cx={650+(i*119)%680} cy={100+(i*83)%650} r={i%7===0?4:1.3} fill={i%3?"#aac3bd":"#d5ac4d"} opacity={.25+(i%4)*.12}/>)}<path d="M650 690Q720 630 790 690T930 690T1070 690T1210 690T1350 690" fill="none" stroke="#8da8d0" strokeOpacity=".45"/></svg>}
