"use client";

import Link from "next/link";
import { useLocale } from "next-intl";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronDown, X } from "lucide-react";

import styles from "./wave-of-thoughts.module.css";

type Sound="silence"|"forest"|"rain"|"ocean";
type Phase="closed"|"beginning"|"active"|"ending"|"noticed"|"reflection";
type Thought={id:number;x:number;y:number;size:number;born:number;life:number;parent?:number;touched:boolean};
type Connection={id:number;from:Thought;to:Thought;born:number};
const EXPERIENCE_MS=180_000, NOTE_KEY="qunara-wave-of-thoughts-reflections";
const audio:Record<Exclude<Sound,"silence">,string>={forest:"forest",rain:"rain",ocean:"ocean"};

const text={
  en:{eyebrow:"Interactive exploration · 3–5 minutes",title:"Wave of Thoughts",lead:"A quiet experience about attention and the movement of mind.",category:"Beginner",sound:"Choose an atmosphere",sounds:{silence:"Silence",forest:"Forest",rain:"Rain",ocean:"Ocean"},enter:"Enter experience",begin:"Begin",exit:"Leave experience",thought:"A passing thought",noticed:"Did you notice?",experience:"Your experience",faded:"Some thoughts faded naturally.",stayed:"Some stayed longer after receiving attention.",surprise:"Did anything surprise you?",journal:"Optional journal",prompt:"What did you notice?",save:"Save on this device",saved:"Saved privately",buddhist:"Buddhist reflection",buddhistBody:"Many meditation traditions encourage observing thoughts without immediately following them. The aim is not to eliminate thinking, but to understand how the mind moves.",quantum:"Quantum perspective",quantumBody:"Quantum physics studies microscopic systems through mathematics and experiments. Observation has a specific meaning in quantum measurement. This experience does not simulate quantum mechanics. It invites reflection on observation from another perspective.",metaphor:"This is a metaphor, not scientific evidence.",boundary:"Where the analogy ends",boundaryBody:"Meditation explores subjective experience. Quantum physics studies physical reality. They are different disciplines. This experience simply invites thoughtful dialogue between them.",next:"Continue exploring",mobius:"The Möbius Strip and Non-Dual Seeing",dependent:"Dependent Origination — Nothing Exists Alone",open:"Open exploration",local:"Your sentence remains in this browser only.",touched:"Thoughts you followed",released:"Thoughts that passed",audio:"Ambient sound"},
  vi:{eyebrow:"Khám phá tương tác · 3–5 phút",title:"Làn Sóng Ý Nghĩ",lead:"Một trải nghiệm yên tĩnh về sự chú ý và chuyển động của tâm.",category:"Dành cho người mới",sound:"Chọn không gian âm thanh",sounds:{silence:"Im lặng",forest:"Rừng",rain:"Mưa",ocean:"Biển"},enter:"Bước vào trải nghiệm",begin:"Bắt đầu",exit:"Rời trải nghiệm",thought:"Một ý nghĩ đang đi qua",noticed:"Bạn có nhận ra?",experience:"Trải nghiệm của bạn",faded:"Một số ý nghĩ tự nhiên tan đi.",stayed:"Một số ở lại lâu hơn khi được chú ý.",surprise:"Có điều gì khiến bạn bất ngờ?",journal:"Ghi lại nếu bạn muốn",prompt:"Bạn đã nhận ra điều gì?",save:"Lưu trên thiết bị",saved:"Đã lưu riêng tư",buddhist:"Góc nhìn Phật học",buddhistBody:"Nhiều truyền thống thiền khuyến khích ta quan sát ý nghĩ mà không lập tức chạy theo. Mục đích không phải loại bỏ suy nghĩ, mà là hiểu tâm vận hành như thế nào.",quantum:"Góc nhìn lượng tử",quantumBody:"Vật lý lượng tử nghiên cứu các hệ vi mô bằng toán học và thực nghiệm. Quan sát mang một ý nghĩa chuyên biệt trong phép đo lượng tử. Trải nghiệm này không mô phỏng cơ học lượng tử. Nó chỉ mời ta suy ngẫm về sự quan sát từ một góc nhìn khác.",metaphor:"Đây là một ẩn dụ, không phải bằng chứng khoa học.",boundary:"Nơi phép so sánh dừng lại",boundaryBody:"Thiền khám phá trải nghiệm chủ quan. Vật lý lượng tử nghiên cứu thực tại vật lý. Đây là hai lĩnh vực khác nhau. Trải nghiệm này chỉ mở ra một cuộc đối thoại thận trọng giữa chúng.",next:"Tiếp tục khám phá",mobius:"Dải Möbius và Cách Nhìn Bất Nhị",dependent:"Duyên Khởi — Không Gì Tồn Tại Đơn Độc",open:"Mở bài khám phá",local:"Câu viết của bạn chỉ được lưu trong trình duyệt này.",touched:"Ý nghĩ bạn đã theo",released:"Ý nghĩ đã đi qua",audio:"Âm thanh nền"}
} as const;

export function WaveOfThoughts(){
  const locale=useLocale()==="vi"?"vi":"en",t=text[locale];
  const [phase,setPhase]=useState<Phase>("closed"),[sound,setSound]=useState<Sound>("silence"),[thoughts,setThoughts]=useState<Thought[]>([]),[connections,setConnections]=useState<Connection[]>([]),[touched,setTouched]=useState(0),[appeared,setAppeared]=useState(0),[note,setNote]=useState(""),[saved,setSaved]=useState(false),[recommendMobius,setRecommendMobius]=useState(true);
  const ambientRef=useRef<HTMLAudioElement>(null),bellRef=useRef<HTMLAudioElement>(null),rippleRef=useRef<HTMLAudioElement>(null),toneRef=useRef<HTMLAudioElement>(null),timers=useRef<number[]>([]),lastTouch=useRef(0),nextId=useRef(1),fadeFrame=useRef<number>();
  const clearTimers=useCallback(()=>{timers.current.forEach(window.clearTimeout);timers.current=[]},[]);
  const fade=useCallback((element:HTMLAudioElement|null,target:number,done?:()=>void)=>{if(!element)return;cancelAnimationFrame(fadeFrame.current??0);const from=element.volume,start=performance.now();const step=(now:number)=>{const progress=Math.min(1,(now-start)/2000);element.volume=from+(target-from)*progress;if(progress<1)fadeFrame.current=requestAnimationFrame(step);else done?.()};fadeFrame.current=requestAnimationFrame(step)},[]);
  const play=useCallback((element:HTMLAudioElement|null,volume:number)=>{if(!element)return;element.currentTime=0;element.volume=volume;void element.play().catch(()=>{})},[]);
  const makeThought=useCallback((parent?:Thought):Thought=>{const angle=Math.random()*Math.PI*2,distance=8+Math.random()*12;return{id:nextId.current++,x:parent?Math.max(8,Math.min(92,parent.x+Math.cos(angle)*distance)):10+Math.random()*80,y:parent?Math.max(12,Math.min(88,parent.y+Math.sin(angle)*distance)):14+Math.random()*72,size:32+Math.random()*52,born:Date.now(),life:6000+Math.random()*6000,parent:parent?.id,touched:false}},[]);
  const addThought=useCallback((parent?:Thought)=>{const next=makeThought(parent);setThoughts(current=>current.length>=5?current:[...current,next]);setAppeared(n=>n+1);play(toneRef.current,.055);return next},[makeThought,play]);

  useEffect(()=>{try{const completed=JSON.parse(localStorage.getItem("qunara-interactive-complete")||"[]") as string[];setRecommendMobius(!completed.includes("mobius")&&!localStorage.getItem("qunara-mobius-visited"))}catch{}},[]);
  useEffect(()=>{if(phase==="closed")return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){clearTimers();ambientRef.current?.pause();setPhase("closed");setThoughts([]);setConnections([])}};window.addEventListener("keydown",escape);document.body.style.overflow="hidden";return()=>{window.removeEventListener("keydown",escape);document.body.style.overflow=""}},[phase,clearTimers]);
  useEffect(()=>()=>{clearTimers();cancelAnimationFrame(fadeFrame.current??0);document.body.style.overflow=""},[clearTimers]);
  useEffect(()=>{if(phase!=="active")return;const interval=window.setInterval(()=>{const now=Date.now();setThoughts(current=>{const living=current.filter(item=>now-item.born<item.life);const calm=now-lastTouch.current>12_000;if(calm&&living.length>1)return living.slice(-1);return living});setConnections(current=>current.filter(line=>now-line.born<3500));setThoughts(current=>{const calm=now-lastTouch.current>12_000,limit=calm?1:5;if(current.length<limit&&Math.random()>.64){const next=makeThought();setAppeared(n=>n+1);play(toneRef.current,.045);return [...current,next]}return current})},900);return()=>window.clearInterval(interval)},[phase,makeThought,play]);

  function open(){setPhase("beginning");setThoughts([]);setConnections([]);setTouched(0);setAppeared(0);setSaved(false)}
  function begin(){setPhase("active");lastTouch.current=Date.now();if(sound!=="silence"&&ambientRef.current){ambientRef.current.volume=0;void ambientRef.current.play().then(()=>fade(ambientRef.current,.22)).catch(()=>{})}timers.current.push(window.setTimeout(()=>addThought(),4000));timers.current.push(window.setTimeout(end,EXPERIENCE_MS))}
  function end(){clearTimers();setPhase("ending");fade(ambientRef.current,0,()=>ambientRef.current?.pause());timers.current.push(window.setTimeout(()=>{setThoughts([]);setConnections([]);play(bellRef.current,.42)},900));timers.current.push(window.setTimeout(()=>setPhase("noticed"),2900));timers.current.push(window.setTimeout(()=>setPhase("reflection"),5900))}
  function close(){clearTimers();fade(ambientRef.current,0,()=>ambientRef.current?.pause());setPhase("closed");setThoughts([]);setConnections([])}
  function touch(thought:Thought){if(thought.touched)return;lastTouch.current=Date.now();setTouched(n=>n+1);play(rippleRef.current,.1);const count=Math.min(3,1+Math.floor(Math.random()*3));const children=Array.from({length:count},()=>makeThought(thought));setThoughts(current=>[...current.map(item=>item.id===thought.id?{...item,touched:true,life:item.life+3500}:item),...children].slice(-5));setAppeared(n=>n+children.length);setConnections(current=>[...current,...children.map(child=>({id:child.id,from:thought,to:child,born:Date.now()}))])}
  function saveNote(event:FormEvent){event.preventDefault();if(!note.trim())return;const current=JSON.parse(localStorage.getItem(NOTE_KEY)||"[]") as unknown[];localStorage.setItem(NOTE_KEY,JSON.stringify([{date:new Date().toISOString(),note:note.trim().slice(0,180),touched,appeared},...current].slice(0,50)));setSaved(true)}
  const released=Math.max(0,appeared-touched),activity=Math.min(1,touched/10),recommendation=useMemo(()=>recommendMobius?{title:t.mobius,href:`/${locale}/interactive/mobius`}:{title:t.dependent,href:locale==="vi"?"/vi/kham-pha/duyen-khoi":"/en/explore/dependent-origination"},[recommendMobius,t,locale]);

  return <section className={styles.launch} aria-labelledby="wave-title"><div className={styles.launchCopy}><p className="q-kicker">05 · {t.eyebrow}</p><h2 id="wave-title">{t.title}</h2><p>{t.lead}</p><span>{t.category}</span></div><div className={styles.launchControl}><fieldset><legend>{t.sound}</legend>{(["silence","forest","rain","ocean"] as Sound[]).map(item=><button type="button" aria-pressed={sound===item} onClick={()=>setSound(item)} key={item}>{t.sounds[item]}</button>)}</fieldset><button className={styles.enter} onClick={open}>{t.enter}<ArrowRight/></button></div>
    {phase!=="closed"&&<div className={`${styles.overlay} ${styles[phase]}`} style={{"--activity":activity} as React.CSSProperties} role="dialog" aria-modal="true" aria-label={t.title}>
      <button className={styles.close} onClick={close} aria-label={t.exit}><X/></button>
      {phase==="beginning"&&<button className={styles.begin} onClick={begin}>{t.begin}</button>}
      {(phase==="active"||phase==="ending")&&<div className={styles.field} aria-live="off"><svg aria-hidden="true">{connections.map(line=><line key={line.id} x1={`${line.from.x}%`} y1={`${line.from.y}%`} x2={`${line.to.x}%`} y2={`${line.to.y}%`}/>)}</svg>{thoughts.map(item=><button key={item.id} className={`${styles.thought} ${item.touched?styles.touched:""}`} style={{left:`${item.x}%`,top:`${item.y}%`,width:item.size,height:item.size,"--life":`${item.life}ms`} as React.CSSProperties} onClick={()=>touch(item)} aria-label={t.thought}><i/></button>)}</div>}
      {phase==="noticed"&&<p className={styles.notice}>{t.noticed}</p>}
      {phase==="reflection"&&<div className={styles.results}><header><p className="q-kicker">{t.experience}</p><h2>{t.noticed}</h2></header><div className={styles.observations}><p>{t.faded}</p><p>{t.stayed}</p><p>{t.surprise}</p><dl><div><dt>{t.touched}</dt><dd>{touched}</dd></div><div><dt>{t.released}</dt><dd>{released}</dd></div></dl></div><form onSubmit={saveNote}><label htmlFor="wave-note">{t.journal}</label><div><input id="wave-note" value={note} maxLength={180} onChange={event=>setNote(event.target.value)} placeholder={t.prompt}/><button disabled={!note.trim()||saved}>{saved?<Check/>:null}{saved?t.saved:t.save}</button></div><small>{t.local}</small></form><div className={styles.reflections}><details><summary>{t.buddhist}<ChevronDown/></summary><p>{t.buddhistBody}</p></details><details><summary>{t.quantum}<ChevronDown/></summary><p>{t.quantumBody}</p><strong>{t.metaphor}</strong></details></div><aside className={styles.boundary}><b>{t.boundary}</b><p>{t.boundaryBody}</p></aside><footer><div><span>{t.next}</span><h3>{recommendation.title}</h3></div><Link href={recommendation.href} onClick={()=>{if(recommendMobius)localStorage.setItem("qunara-mobius-visited","true")}}>{t.open}<ArrowRight/></Link></footer></div>}
      <span className={styles.srStatus} aria-live="polite">{phase==="noticed"?t.noticed:phase==="reflection"?t.experience:""}</span>
      <audio ref={ambientRef} src={sound==="silence"?undefined:`/audio/meditation/${audio[sound]}.wav`} loop preload="none"/><audio ref={bellRef} src="/audio/meditation/bell.wav" preload="auto"/><audio ref={toneRef} src="/audio/meditation/air-tone.wav" preload="auto"/><audio ref={rippleRef} src="/audio/meditation/ripple.wav" preload="auto"/>
    </div>}
  </section>
}
