"use client";

import {FormEvent,useEffect,useState} from "react";
import {Bookmark,Highlighter,MessageCircleQuestion,NotebookPen,Save,X} from "lucide-react";
import {useTranslations} from "next-intl";
import type {LocalizedChapter} from "@/lib/learn-localized-content";

type Panel="notes"|"ask"|"highlights"|null;
export function VietnameseReaderTools({chapter}:{chapter:LocalizedChapter}){
  const t=useTranslations("learn");const key=`${chapter.path}/${chapter.englishSlug}`;const [progress,setProgress]=useState(0);const [bookmarked,setBookmarked]=useState(false);const [panel,setPanel]=useState<Panel>(null);const [notes,setNotes]=useState("");const [highlights,setHighlights]=useState<string[]>([]);const [question,setQuestion]=useState("");const [answer,setAnswer]=useState("");const [streak,setStreak]=useState(1);
  useEffect(()=>{setBookmarked((JSON.parse(localStorage.getItem("qunara-bookmarks")||"[]") as string[]).includes(key));setNotes(localStorage.getItem(`qunara-note-${key}`)||"");setHighlights(JSON.parse(localStorage.getItem(`qunara-highlights-${key}`)||"[]") as string[]);const today=new Date().toDateString(),last=localStorage.getItem("qunara-learn-last-day"),current=Number(localStorage.getItem("qunara-learn-streak")||"0"),yesterday=new Date(Date.now()-86400000).toDateString(),next=last===today?Math.max(1,current):last===yesterday?current+1:1;localStorage.setItem("qunara-learn-last-day",today);localStorage.setItem("qunara-learn-streak",String(next));setStreak(next);const scroll=()=>{const el=document.documentElement;setProgress(Math.min(100,Math.max(0,el.scrollTop/(el.scrollHeight-el.clientHeight)*100)))};window.addEventListener("scroll",scroll,{passive:true});return()=>window.removeEventListener("scroll",scroll)},[key]);
  function bookmark(){const saved=JSON.parse(localStorage.getItem("qunara-bookmarks")||"[]") as string[];const next=bookmarked?saved.filter(x=>x!==key):Array.from(new Set([...saved,key]));localStorage.setItem("qunara-bookmarks",JSON.stringify(next));setBookmarked(!bookmarked)}
  function capture(){const text=window.getSelection()?.toString().trim();if(!text||text.length<3)return;const next=Array.from(new Set([...highlights,text])).slice(-12);setHighlights(next);localStorage.setItem(`qunara-highlights-${key}`,JSON.stringify(next));setPanel("highlights");window.getSelection()?.removeAllRanges()}
  function ask(event:FormEvent){event.preventDefault();if(!question.trim())return;setAnswer(`${chapter.lesson[0]} ${chapter.takeaways.join(" ")}`)}
  return <><div className="reader-progress" style={{width:`${progress}%`}}/><aside className="reader-tools" aria-label={t("readingTools")}><button onClick={bookmark} className={bookmarked?"active":""} aria-label={bookmarked?t("removeBookmark"):t("bookmark")}><Bookmark fill={bookmarked?"currentColor":"none"}/><span>{t("save")}</span></button><button onClick={()=>setPanel(panel==="notes"?null:"notes")}><NotebookPen/><span>{t("notes")}</span></button><button onClick={capture}><Highlighter/><span>{t("highlight")}</span></button><button onClick={()=>setPanel(panel==="ask"?null:"ask")}><MessageCircleQuestion/><span>{t("ask")}</span></button><i>{streak} {t("day")}</i></aside>{panel&&<aside className="reader-panel"><button className="reader-close" onClick={()=>setPanel(null)} aria-label={t("close")}><X/></button>{panel==="notes"&&<><p>{t("privateNotes")}</p><h2>{t("remember")}</h2><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={t("notesPlaceholder")}/><button className="reader-save" onClick={()=>localStorage.setItem(`qunara-note-${key}`,notes)}><Save/>{t("saveDevice")}</button></>}{panel==="highlights"&&<><p>{t("savedHighlights")}</p><h2>{t("pausedWords")}</h2>{highlights.length?highlights.map(x=><blockquote key={x}>“{x}”</blockquote>):<small>{t("highlightHint")}</small>}</>}{panel==="ask"&&<><p>{t("askQunara")}</p><h2>{t("difficult")}</h2><small>{t("assistantBoundary")}</small><form onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t("askPlaceholder",{title:chapter.title.toLowerCase()})}/><button>{t("ask")}</button></form>{answer&&<blockquote>{answer}</blockquote>}</>}</aside>}</>;
}
